### ISSUE TITLE
Autocomplete does not respect initial value

### ISSUE THREAD

**Issue by SQReder** [lookfirst/mui-rff#101]
**Describe the bug**
Autocomplete does not respect initial form field value.

**To Reproduce**
Demo https://codesandbox.io/s/mui-rff-autocomplete-default-value-96u9p

**Expected behavior**
Autocomplete must use initial value.

**Screenshots**
![image](https://user-images.githubusercontent.com/1519753/73262446-37543780-41df-11ea-9b4a-d511057f04b4.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 79.0.3945.130

**Comment by SQReder** [comment]
Ok, make a workaround. However, it has ts warnings and kinda dirty.

```ts
  const initialValues = { currency: "eur" };

  const options = [
    { label: "USD", value: "usd" },
    { label: "EUR", value: "eur" }
  ];

  const defaultValue = options.find(o => o.value === initialValues.currency);

  <Autocomplete
    name="currency"
    label="Currency"
    options={options}
    defaultValue={defaultValue}
    getOptionValue={x => x.value}
    getOptionLabel={x => x.label}
  />
```

https://codesandbox.io/s/mui-rff-autocomplete-default-value-9gzct

**Comment by lookfirst** [comment]
Hey there, thank you so much for the report. I'm trying to understand why the codesandbox has warnings even on the imports... it says that it cannot find the module. Is there something wrong with the tsconfig file?

![image](https://user-images.githubusercontent.com/85355/73276874-38b14000-419e-11ea-935b-0db90feabead.png)

**Comment by SQReder** [comment]
It's a bug of CodeSandbox itself. Try to remove all the deps from package.json, save and put it back to flush deps cache.

**Comment by lookfirst** [comment]
i'm working on this, but having some issues with types that i'm trying to work out... =(

**Comment by aaronhayes** [comment]
@lookfirst if you need some help on this one I can probably help out soon

**Comment by lookfirst** [comment]
@aaronhayes thanks... i've been a bit slammed with work (sitting in meetings) the last couple days, but should have some time this weekend. i've got a bunch of changes in flight, but haven't pushed them yet.

**Comment by lookfirst** [comment]
@aaronhayes @SQReder Should be fixed now, this was a bit tricky and I'm not 100% in love with the solution, but it works. I was also held up with a bug in 4.9.0 of mui with types that is fixed now.

**Comment by jasonburnell98** [comment]
Still looking for a fix if initialValues are not in direct access...
