### ISSUE TITLE
Update Yup to v1.x

### ISSUE THREAD

**Issue by lookfirst** [lookfirst/mui-rff#1035]
Yup has an API change in v1.x where the 'required' field is no longer working with makeValidate. It now uses an API called `.describe()`

Need to update the package.json to 1.x and update makeValidate to work as well.

**Comment by mschilde** [comment]
Sooo... any update on this?

**Comment by mortezaalizadeh** [comment]
> Sooo... any update on this?

I am also desperatly waiting for this to be released

**Comment by lookfirst** [comment]
I've been trying to get this to work with 1.x of yup and it just isn't working. I really don't know what the issue is. Super annoying.

**Comment by lookfirst** [comment]
@maccuaa... want to look into this?

**Comment by lookfirst** [comment]
Yup exposes 'nullable' and 'optional' in the object returned from describe()... neither of these seem to make any of the tests pass.

**Comment by maccuaa** [comment]
@lookfirst sorry I don't use yup in any of my projects so I don't have any experience with it
