### ISSUE TITLE
Upgrade to date picker v6?

### ISSUE THREAD

**Issue by yann-combarnous** [lookfirst/mui-rff#1043]
**Is your feature request related to a problem? Please describe.**
MUI date pickers have been updated to v6, see https://mui.com/x/migration/migration-pickers-v5/

**Describe the solution you'd like**
New major version for date picker v6.

**Comment by lookfirst** [comment]
Nice. Bit busy with a house remodel at the moment... PR's welcome! =)

**Comment by maccuaa** [comment]
Closed by #1074
