### ISSUE TITLE
[Autocomplete] Initial values can't sets

### ISSUE THREAD

**Issue by popuguytheparrot** [lookfirst/mui-rff#107]
**Describe the bug**
Autocomplete dont pass initial value to Textfield component

**To Reproduce**
1. Open example
2. See nothing in autocomplete value

**Current behavior** 
https://codesandbox.io/s/react-final-form-material-ui-example-gzx4p

**Expected behavior**
Initial values setted

**Comment by lookfirst** [comment]
Thank you for the report... I'm going to close in favor of #101
