### ISSUE TITLE
v6.2.0 has incorrect peer dependency

### ISSUE THREAD

**Issue by maccuaa** [lookfirst/mui-rff#1078]
v6.2.0 in NPM still has the `"@mui/x-date-pickers": "^5.0.1",` as the peerDependency which is 
incorrect. This is causing npm install to fail.

```
npm ERR! Found: @mui/x-date-pickers@6.9.2
npm ERR! node_modules/@mui/x-date-pickers
npm ERR!   @mui/x-date-pickers@"6.9.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @mui/x-date-pickers@"^5.0.1" from mui-rff@6.2.0
```

Source: https://www.npmjs.com/package/mui-rff/v/6.2.0?activeTab=code

**Comment by lookfirst** [comment]
yea, not idea what happened there.

i'll do a 6.2.1 release soon.

**Comment by lookfirst** [comment]
let's hope 6.2.2 fixes it.
