### ISSUE TITLE
Cannot find module  mui-rff or its corresponding type declarations.

### ISSUE THREAD

**Issue by criscola** [lookfirst/mui-rff#1080]
**Describe the bug**

TS compiler complains: Cannot find module  mui-rff or its corresponding type declarations when trying to use the package.

**To Reproduce**

I used npm to install the packages as described in the README.

**Expected behavior**

I expected to not get this error.

React version: 18.2.0

**Comment by criscola** [comment]
Nevermind, for some reason "npm add" didn't add the dependencies.

**Comment by lookfirst** [comment]
No worries, glad it worked out for you. I stopped using npm ages ago though... yarn or even pnpm have had better results for me.
