### ISSUE TITLE
Demo page/Playground is not working

### ISSUE THREAD

**Issue by lukas-cc** [lookfirst/mui-rff#1081]
**Describe the bug**
The demo page is not working.

**To Reproduce**
1. Go to [lookfirst.github.io/mui-rff/](https://lookfirst.github.io/mui-rff/)
2. Open developer tools to see the errors

**Expected behavior**
Demo page should be working and showcasw all the components that mui-rff provides.

**Screenshots**
<img width="1435" alt="image" src="https://github.com/lookfirst/mui-rff/assets/52623639/3f56816c-9cce-4585-b1a1-51961bfaa0a7">

**Comment by lookfirst** [comment]
Oh wow, that's a first. I'll look into that today. Thanks for pointing it out!

**Comment by lookfirst** [comment]
Finally got around to fixing this. Turns out that parcel 2.8.3 broke something and i had ^2.8.0 of package.json and just happened to get a bad build.

2.9.3 fixes things. i've pegged the version in the package.json so that it doesn't break randomly again.
