### ISSUE TITLE
date-fns doesn't accept strings as date arguments. Please use `parseISO` to parse strings

### ISSUE THREAD

**Issue by ErikParso** [lookfirst/mui-rff#1083]
In form values, when date value is undefined, date-fns lib throws the following error

date-fns doesn't accept strings as date arguments. Please use `parseISO` to parse strings

This is caused by empty string beeing passed as value to MUI datepickers textfield 

![image](https://github.com/lookfirst/mui-rff/assets/35962203/f4983abe-007a-4d48-b9f6-c7a66cecdd2f)

Simple value check (same as in line above) should work

![image](https://github.com/lookfirst/mui-rff/assets/35962203/149258d5-6be6-4f21-8f2d-4f86108a9480)

**Comment by ErikParso** [comment]
Sure thing (https://github.com/lookfirst/mui-rff/pull/1084)

**Comment by lookfirst** [comment]
Released as 7.2.0 thanks again!
