### ISSUE TITLE
TextField type restriction?

### ISSUE THREAD

**Issue by zhuangya** [lookfirst/mui-rff#116]
**Describe the bug**

For `<TextField />`'s `type` prop, there is a restriction here:

https://github.com/lookfirst/mui-rff/blob/54e730400b7bde6b5f134d5cb71040fa38d3b951/src/TextField.tsx#L14

However, in [@material-ui](https://github.com/mui-org/material-ui/blob/f567b384f509d36b7e10f691e6b58538e7db8869/packages/material-ui/src/TextField/TextField.js#L337) there is no such limitation but only refer it to HTML standard ([linked here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Form_%3Cinput%3E_types))

why only allow types like `password` `text` `email` `number` and `url`?

shouldn't it also support other types such as `tel` ?

**To Reproduce**

```typescript

<TextField type='tel' />
                  ^ typescript would complain about this type

```

**Expected behavior**

accept all valid html input type

**Screenshots**

![image](https://user-images.githubusercontent.com/499038/74120759-a417fa80-4bff-11ea-9746-ddd14784e1d2.png)

**Desktop (please complete the following information):**
 - OS: mac OS X 10.15.2
 - Browser Chrome
 - Version 80

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lookfirst** [comment]
Thank you so much for the report. Yea, we changed this not too long ago and it bugged me, but I 🤷‍♂ 'd it off until someone else (you) would bring it up. Would you like to submit a PR for this? It should be a pretty easy fix.

**Comment by zhuangya** [comment]
hold my beer: #117

**Comment by lookfirst** [comment]
🍺

**Comment by lookfirst** [comment]
1.8.1
