### ISSUE TITLE
normalizeValidationError function returns only one error for nested form elements.

### ISSUE THREAD

**Issue by vanya829** [lookfirst/mui-rff#1166]
**Describe the bug**
The normalizeValidationError function in the mui-rff repository has an issue handling nested error paths within the errors object. The condition (path && errors.hasOwnProperty(path)) checks for a direct property named path on the errors object. This works for simple paths like "firstName" but fails for nested structures like "test.firstName". Since nested paths don't exist initially, the function never stores errors under them.

**To Reproduce**
1. Go to https://codesandbox.io/p/sandbox/mui-rff-multiple-errors-pq587r?file=%2Fsrc%2FApp.tsx
2. See two fields with the same validation configuration
3. Type few symbols
4. See that "firstName" field shows two validation errors, but "test.firstName" only one, the last one.

**Expected behavior**
Validation should work the same for both fields, no matter whether it is nested or not.

**Screenshots**
<img width="1467" alt="image" src="https://github.com/lookfirst/mui-rff/assets/1397979/0e7d9b82-5e10-4a8c-882c-43649de6bba9">

**Additional context**
The problem is in condition https://github.com/lookfirst/mui-rff/blob/f531eee0fed0d5323fc56782697dab8e6d8826b5/src/Validation.ts#L49. Simple change from `errors.hasOwnProperty(path)` to `get(errors, path)` should resolve the issue.

**Comment by lookfirst** [comment]
Interesting suggestion for a resolution, would you like to submit a PR and make sure that tests pass?

**Comment by lookfirst** [comment]
Great work, thanks!
