### ISSUE TITLE
8.0.1 update

### ISSUE THREAD

**Issue by maccuaa** [lookfirst/mui-rff#1177]
[mui-rff v8.0.0](https://www.npmjs.com/package/mui-rff/v/8.0.0) is marked as deprecated in NPM with a note:

> incomplete release, please wait for 8.0.1

I'm not seeing any open PRs or issues in this repo that mention any problems with 8.0.0. What issues are there with the release? Anything you need help with?

**Comment by lookfirst** [comment]
Sorry! Due to a bug in node. Been waiting for brew to have it available.

https://github.com/lookfirst/mui-rff/discussions/1176

Going to close this in favor of the above discussion.

**Comment by lookfirst** [comment]
@maccuaa I've published 8.0.1 now.
