### ISSUE TITLE
[bug] single checkbox and switch increment render count

### ISSUE THREAD

**Issue by lookfirst** [lookfirst/mui-rff#124]
**Describe the bug**

Open up the [demo](https://lookfirst.github.io/mui-rff/) and click on the single switch or the single checkbox and watch the render count increment each time you click on it.

If you then click on another component and click on one of the singles, the render count does not increment any more.

It is quite unclear where this issue is stemming from!

**Expected behavior**

Render count maybe increments once, but does not increment on subsequent clicks. Similar to the same variation of the components in their multiple configuration.

**Comment by lookfirst** [comment]
Sadly, the above didn't fix this... not sure where the issue is...

**Comment by DASPRiD** [comment]
@lookfirst We should revalidate this issue with the latest improvements. Although with the underlying (not yet fixed) bug in react-final-form, which results in circular updates, it might still be present.

**Comment by lookfirst** [comment]
Yep, still present. I also fear RFF isn't going to get updated much... and damn, it really needs to be done in typescript with tons of testing.
