### ISSUE TITLE
Cannot pass displayEmpty to Select

### ISSUE THREAD

**Issue by lookfirst** [lookfirst/mui-rff#129]
**Describe the bug**
Cannot pass displayEmpty (and other properties) to select element.

[Related](https://github.com/lookfirst/mui-rff/issues/69#issuecomment-590309859)

**Comment by lookfirst** [comment]
@AlessandroAnnini, this has been released.

**Comment by AlessandroAnnini** [comment]
thanks!!

**Comment by AlessandroAnnini** [comment]
but at this point shouldn't this be working?
[![Edit priceless-snowflake-29git](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/priceless-snowflake-29git?fontsize=14&hidenavigation=1&theme=dark)

if i do not initialize the select and i use `displayEmpty` prop

**Comment by lookfirst** [comment]
You haven't defined any initialValues.

https://codesandbox.io/s/great-glade-bjh8z

**Comment by AlessandroAnnini** [comment]
Hi, sorry to bother again but I think this is not the right behaviour:
I made another super-simple example with final-form only: initialValues are not mandatory, and I can have a select anyway...

have a look, that's what I am looking for:

[![Edit peaceful-hopper-pynrh](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/peaceful-hopper-pynrh?fontsize=14&hidenavigation=1&theme=dark)

**Comment by lookfirst** [comment]
@AlessandroAnnini Ok, I'll take a look. I'm in the middle of a huge internal refactor right now, so it may be a few days before I get to it, but it is on my plate.

**Comment by lookfirst** [comment]
Hi @AlessandroAnnini ... 

The error comes from Material-UI, there is nothing I can do about it. Your example does not use Material-UI, so that is why it is working.

https://codesandbox.io/s/fast-smoke-jgg79

**Comment by lookfirst** [comment]
Actually, I just updated the above example and removed `multiple={true}`, so now it works.

**Comment by AlessandroAnnini** [comment]
Thanks lookfirst, this is amazing! do you think it could work with multiple choice too?

**Comment by lookfirst** [comment]
@AlessandroAnnini yes, declare the inputValues... even as a []. ;-)

**Comment by AlessandroAnnini** [comment]
@lookfirst, I'm sorry, maybe I was not clear but I wanted to avoid the use of initialValues, and I cannot find another way, if there is one maybe I cannot see it. If you can make it work with multiple select and no initialValues could you please fork the sandbox?
thanks so much!

**Comment by lookfirst** [comment]
Please explain your aversion to initialValues.

**Comment by AlessandroAnnini** [comment]
my goal:
i want to be able to build a complete working form starting from a json schema of the object that I want as output of the form's submit value. This should work for every kind of object, including arrays. If I have an array of objects in my json schema, the inner object should "translate" on the UI as a button on the form that I can use to add a nested form for with the fields reflecting the properties of the inner object.

my problem:
if I have to specify `initialValues` at the beginning it means that I have to write the object with nested arrays of string before everything, this will result in a wrong form UI because this will force the form to draw the nested part before I actually request for one, this just because I had to give an `initialValues` object
I will post a codesandbox as soon as I can

**Comment by AlessandroAnnini** [comment]
Hi @lookfirst 
I finally managed to set up a codesandbox about my experiment: https://codesandbox.io/s/dynamic-form-test-35lk1

ask me anything

**Comment by lookfirst** [comment]
@AlessandroAnnini I think I've got a fix for you now. =) Please try v2.1.6

**Comment by AlessandroAnnini** [comment]
Thanks, that's just beautiful! I updated my code, it works perfectly, I updated the last codesandbox..
What do you say about my idea of going from a json schema to a fully working dynamic form?

**Comment by lookfirst** [comment]
Yes, having a schema is great. I just implemented [a basic one](https://github.com/covid-md/survey-web/blob/master/public/model.json) for a covid site I was helping with.

This guy is working on the best one for transforming the schema to Yup for validation...

https://github.com/ritchieanesco/json-schema-yup-transform

**Comment by AlessandroAnnini** [comment]
nice!!
