### ISSUE TITLE
Need A Example With lasted @material-ui/pickers

### ISSUE THREAD

**Issue by Vn-ChemGio** [lookfirst/mui-rff#145]
In @material-ui/pickers
lasted version is "^4.0.0-alpha.3" had been relase but

> There is no more Keyboard* components exported (like KeyboardDatePicker). From now any picker will allow keyboard input. For mobile, it is possible using the "pen" icon inside the dialog.

In lasted version, using date picker, time picker or date time picker is so easily and simply than ver 3.x
So need a build or example with it

**Comment by lookfirst** [comment]
Thanks for your comments! Pickers v4 is being tracked in [another issue](#106), so I'm going to close this as a duplicate. 

It will require a v2 of mui-rff.

I'm currently in the middle off fixing [another issue](#141 ), so don't have time to work on this quite yet.
