### ISSUE TITLE
Select label is under outline when using outline variant

### ISSUE THREAD

**Issue by cyberwombat** [lookfirst/mui-rff#159]
**Describe the bug**
When using a Select with outline variant the label is under the outline.

**To Reproduce**
```
<Select
  name="topic"
  label="Select a topic"
  formControlProps={{
    variant: 'outlined'
  }}
>
  <MenuItem value="general">General support</MenuItem>
</Select>
```

**Screenshots**
<img width="739" alt="Screen Shot 2020-03-11 at 9 43 28 AM" src="https://user-images.githubusercontent.com/777498/76441675-0b4ed900-637d-11ea-8045-d36226b2c73c.png">

**Desktop (please complete the following information):**
 - Version 2.0,0

**Comment by cyberwombat** [comment]
Hmm. I see there are previously closed bug reports on this. I looked at the sandbox and the fix is to evidently add `variant="outlined"` in both places:
```
<Select
  name="topic"
  label="Select a topic"
  variant="outlined"
  formControlProps={{
    variant: 'outlined'
  }}
>
  <MenuItem value="general">General support</MenuItem>
</Select>
```
is that really how it is meant to be?

**Comment by lookfirst** [comment]
Definitely not intended. Did you try removing it from the formControlProps and leaving it on the component?

**Comment by lookfirst** [comment]
Also, thanks for the submission... once you figure it out, I'll update my documentation to make it clear. It definitely needs to be on the MUI-RFF component because I have to do some magic to make it all work. The MUI website doesn't really document this hackery very clearly... it is just buried in their example code.

**Comment by cyberwombat** [comment]
Ya that messes up the format:
<img width="753" alt="Screen Shot 2020-03-11 at 10 13 18 AM" src="https://user-images.githubusercontent.com/777498/76444303-fecc7f80-6380-11ea-8d50-a738d3bb5072.png">

**Comment by lookfirst** [comment]
I get it. Ok, thanks! I'll fix that right away.

**Comment by lookfirst** [comment]
Ok, please try now and let me know. v2.0.1. One problem with snapshot testing is you can't 'see' the output. When I fixed this, it broke the snapshot on the outlined test, by adding an `outlined` class to the FormControl. My bad, I should have noticed it was missing, but now at least I know it won't break again without telling me.

**Comment by cyberwombat** [comment]
My form is so beautiful now :) thank you for getting that so quick!

**Comment by lookfirst** [comment]
@cyberwombat Even better is that your code is beautiful. Using this is such a magical way to do forms.
