### ISSUE TITLE
React >=16.13.0 error with conditional fields

### ISSUE THREAD

**Issue by DASPRiD** [lookfirst/mui-rff#166]
This took me a while to figure out, so I'll try to explain it as simple as possible. First off, this problem was introduces with React 16.13.0, see here:
https://reactjs.org/blog/2020/02/26/react-v16.13.0.html#warnings-for-some-updates-during-render

The error message received on the console is the following:
> Warning: Cannot update a component from inside the function body of a different component.

Simplified reproduction case (just hit the checkbox and watch the console):
https://codesandbox.io/s/pensive-panini-3jmhf

In that simplified example, the warning only occurs when there's at least one more mui-rff component present, like the TextField at the top. Getting rid of it or replacing it with a standard Field from react-final-form will not yield the error anymore.

I was not able to figure out what exactly causes the warning to be triggered, but I hope the test case can help you analyse it. I'm not even sure if this is actually a bug of mui-rff or if it is caused by react-final-form.

If you need any more information, just tell me.

**Comment by lookfirst** [comment]
Thanks for the report, but LOL! This is a new one and I immediately see your confusion.

You don't need to wrap MUI-RFF components in a `<Field>` as they already have all that contained within. Please take a look at the existing example, code sandbox, etc mentioned in the readme file for examples and directions on how to do things.

You're welcome to continue discussing this here, but I'm going to close it as invalid.

Cheers.

**Comment by DASPRiD** [comment]
Actually you might misunderstand the example. The wrapping with an additional field is actually for observing the value change of another field, as demonstrated in an official example here:

https://codesandbox.io/s/lm4p3m92q

So please re-open the issue, as this is not invalid.

**Comment by DASPRiD** [comment]
This is apparently already known in react-final-form for conditionally rendered fields, but it seems like they don't have a fix for it yet:

https://github.com/final-form/react-final-form/issues/751

**Comment by lookfirst** [comment]
Double wrapped Fields seems like a very bad idea imho and likely why this is breaking for you. If you want to observe the value change, then useEffect on the FormState.

**Comment by lookfirst** [comment]
Ok, I just looked more deeply at the Conditional example. I'd say don't do it that way. If you want to conditionally display a form field, then use the `useFormState` hook along with useEffect to watch changes for form values and then set a conditional state of what to show/hide in the render method.

Wrapping in a Field just seems like a really bad idea.

**Comment by DASPRiD** [comment]
Well, it is the recommended way by the author's – and as you can see in the linked issue (and the deeper react issue), it was actually a missing check, and the way useField() is currently build is actually wrong.

Apart from that, this error will occur in any way you do conditional fields. But anyway, since this is not a bug of this library but of the dependency, it's fine to leave this as invalid.

**Comment by lookfirst** [comment]
> Well, it is the recommended way by the authors

Seems like it is recommended pre-hooks.

>  But anyway, since this is not a bug of this library but of the dependency, it's fine to leave this as invalid.

Sweet! As soon as it is fixed upstream, I'll make sure to upgrade the hard dependency here.

> Also, using useFormState() is a bad idea, as that way you get more re-renders than actually needed.

Hmm... I'd love to see an example of that!

**Comment by DASPRiD** [comment]
> > Also, using useFormState() is a bad idea, as that way you get more re-renders than actually needed.
> 
> Hmm... I'd love to see an example of that!

Sure, here you go:
https://codesandbox.io/s/admiring-frost-ovef8

Just type a little bit in the text field and see how the `Counter`component keeps rendering all the time. This is definitely an issue in mui-rff, as many components here use `useFormState` for error detection, instead of relying on the `Field` component or `useField()`.

So basically all form elements will get re-rendered all the time right now while just one of them is changing. I was already wondering why I got performance problems with bigger forms :)

**Comment by lookfirst** [comment]
Interesting, I'll definitely look into this.

**Comment by lookfirst** [comment]
Hmm.... why doesn't this show more renders then?

https://codesandbox.io/s/competent-snowflake-qxupj

**Comment by DASPRiD** [comment]
What do you mean? That's the same as mine?

**Comment by DASPRiD** [comment]
But yeah, I think you may just use the FieldState as in the original example:

```jsx
        <Field
          name="bio"
          render={({ input, meta }) => (
            <div>
              <label>Bio</label>
              <textarea {...input} />
              {meta.touched && meta.error && <span>{meta.error}</span>}
            </div>
          )}
        />
```

**Comment by lookfirst** [comment]
Apologies, codesandbox has been acting really flaky for me for some reason. This demonstrates more clearly what is happening right now...

https://codesandbox.io/s/sweet-wescoff-xl4m5

Look at Checkbox for an example of why your above code doesn't work.

**Comment by DASPRiD** [comment]
The counter doesn't go up because it doesn't use `useFormState()`. This one actually demonstrates it better:

https://codesandbox.io/s/sweet-wescoff-xl4m5

As for the checkboxes, I'd argue that that it's weirdly implemented. Checkbox groups should be considered a single field with an array value, just like a select with the `multiple` attribute.

**Comment by lookfirst** [comment]
Submit a PR. =) The tests are already there, so if you think you know a better way, I'm all ears! I'd love to see it done better.

**Comment by DASPRiD** [comment]
I'll look into it. That might become a bigger PR I suppose.

**Comment by lookfirst** [comment]
You posted my same link?

**Comment by DASPRiD** [comment]
Hah yeah, stupid Codesandbox ;)

https://codesandbox.io/s/cold-feather-xft6q

**Comment by lookfirst** [comment]
@DASPRiD I'm making progress with this. Should have something by tomorrow.

**Comment by DASPRiD** [comment]
Alright, if you still need help, I'm fine to hop in and make a PR. I pretty much have it in my head :)

**Comment by lookfirst** [comment]
@DASPRiD Ok, no more useFormState() anywhere in the code. =) v2.1.0

https://codesandbox.io/s/focused-golick-vxhsl

**Comment by DASPRiD** [comment]
Sweet, good job! I still think that the checkbox and radio groups can be improved – I'll make a PR, maybe this weekend, for the checkboxes so you can decide whether you like it or not :)

**Comment by DASPRiD** [comment]
I see that you were watching the issue over at RFF as well – glad they finally resolved that. I'm wondering btw, why isn't react-final-form and material-ui/core a peerDependency in the package.json?

**Comment by lookfirst** [comment]
What about final-form too?

**Comment by lookfirst** [comment]
No reason other than all this stuff is just over complicated madness.

**Comment by lookfirst** [comment]
I tried making rff and ff as a peer...

```
  "sideEffects": false,
  "peerDependencies": {
    "@material-ui/core": "*",
    "final-form": "*",
    "react": ">=16",
    "react-final-form": "*"
  },
  "optionalDependencies": {
    "@date-io/core": "^1.3.13",
    "@date-io/date-fns": "^1.3.13",
    "@material-ui/lab": "^4.0.0-alpha.47",
    "@material-ui/pickers": "^3.2.10",
    "date-fns": "*"
  },
  "devDependencies": {
    "@sheerun/mutationobserver-shim": "*",
    "@testing-library/react": "*",
    "@types/jest": "*",
    "@types/react": "*",
    "@types/react-dom": "*",
    "@types/yup": "*",
    "gh-pages": "*",
    "husky": "*",
    "react": "*",
    "react-dom": "*",
    "tsdx": "*",
    "tslib": "*",
    "typescript": "*",
    "yup": "*"
  }
```

Got this on `tsdx build`...

```
(typescript) Error:/mui-rff/src/Autocomplete.tsx(3,53): semantic error TS2307: Cannot find module 'react-final-form'.
Error: /mui-rff/src/Autocomplete.tsx(3,53): semantic error TS2307: Cannot find module 'react-final-form'.
```

**Comment by DASPRiD** [comment]
Ah, you cannot have them in both peer and dev dependency?

**Comment by lookfirst** [comment]
🤷‍♂ I guess... what is the end goal here?

**Comment by DASPRiD** [comment]
Well, right now installing `mui-rff` is not telling you which other packages you need. Having these in the peer dependencies would make sure that they are installed (and in the supported version range, I wouldn't use `*`).

**Comment by lookfirst** [comment]
Sure, that is valid. I'm kind of agnostic on the * simply because I'm committed to keeping things up to date.

**Comment by DASPRiD** [comment]
Sure, same for me, but e.g.  the minimum requirement for mui-rff is at least react-final-form ^6.0?

**Comment by lookfirst** [comment]
I'm good with that. I'll try to get this in later today.
