### ISSUE TITLE
[feat] Autocomplete doesn't support the `freeSolo` option

### ISSUE THREAD

**Issue by nspaeth** [lookfirst/mui-rff#167]
**Describe the bug**
I can't seem to get the `Autocomplete` component to work correctly with the `freeSolo` option to allow adding new items not already in the list. When typing in an item that doesn't exit and adding it, the item doesn't get added.

**To Reproduce**
1. Add the `freeSolo={true}` prop to the `Autocomplete` component.
2. Type in a new option that doesn't exist in the pre-defined options.
3. Add the option.
4. See that no option is added. If you log the form values you can see that the value is correctly set, but not displayed on the component.

**Expected behavior**
The component should correctly reflect the value of the form.

**Additional context**
I believe that the problem arises here: https://github.com/lookfirst/mui-rff/blob/f734b65123de9fba29223ed1db43f36ee7795015/src/Autocomplete.tsx#L80-L94

The code iterates over `options` and checks the against the `value`, but it should probably be inverted for cases where items are not in `options`. This filtering specifically happens in these lines: https://github.com/lookfirst/mui-rff/blob/f734b65123de9fba29223ed1db43f36ee7795015/src/Autocomplete.tsx#L85-L87

**Comment by lookfirst** [comment]
Thank you for the report. Interesting and good find! Would you like to submit a PR? Please include a unit test as well. =)

**Comment by lookfirst** [comment]
By the way, I'm not a huge fan of the cray cray code for dealing with options like that. If you have a better idea on it, I'm totally open to a refactor.

**Comment by nspaeth** [comment]
Okay. Well, I'm inclined to not check that the value includes valid options, and just include whatever is there.

**Comment by radicand** [comment]
I've been working on a PR for this, after getting into the weeds with it, I believe it'll require a new callback (e.g., `onNewValue(value): void`) so the user can handle the case where a new value is added and decide to append directly to options or do some async action and append something else, etc. It doesn't appear wise/extensible to just assume appending to the options array internally is the best way to handle it.

I've been running into some inherited typing issues preventing me from moving very fast with this, but just wanted to give a heads up and get any feedback on this approach.

**Comment by lookfirst** [comment]
@radicand Off the top of my head, I don't have any suggestions until I see code. Agreed, 99% of my struggle with this has been dealing with type safety. As much as I love types, sometimes it drives me up the wall. =) I want a t-shirt that says: `as any`.

**Comment by radicand** [comment]
I gave up trying to make the type inheritance working and just focused on what needed to change for this to work. Submitted PR #228 with additional details.

**Comment by lookfirst** [comment]
#228 has been closed now, so I'm going to close this one! thanks @radicand

**Comment by Gryndii** [comment]
Is this fixed?
