### ISSUE TITLE
Required fields do not trigger validation until they are changed

### ISSUE THREAD

**Issue by AlexPritchard** [lookfirst/mui-rff#168]
**Describe the bug**
When entering and exiting a required TextField, no validation error message appears. Instead, you have to enter some text, and then clear it to receive the error message.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://codesandbox.io/s/react-final-form-material-ui-example-qdbp2
2. Click inside First Name field
3. Click outside First Name field
4. No validation error appears

**Expected behavior**
The error message "First Name is required" should appear.

**Additional context**
The basic React Final Form example behaves as expected, with the error messages appearing when exiting the field - https://codesandbox.io/s/5vv3m4q4yk

**Comment by lookfirst** [comment]
@AlexPritchard Thank you for the report. You're absolutely right that the behavior is different from the example on the RFF. That said, it is not the only behavior that is acceptable.

Looking at the [Material-UI](https://material.io/components/text-fields/#anatomy) website, it is clear to me that this is effectively undefined behavior. In the one example of validation on that site, you can see it is even happening while typing!

So... I'm starting to think that the right answer here is to somehow enable the ability to configure this behavior. But I think the default should be to fix this for sure. =) My thinking is that we need to figure out if this field is touched or not... but if I remember correctly, I wasn't seeing touched being set correctly in the formState... I can take another pass at this, but I'm slammed right this second volunteer working on a Covid project (even using this library!) ... if you have time to help out here, I'd appreciate it...

**Comment by yoohahn** [comment]
I think it should be configurable. It is not nice to force the user to only one if this type of validations since they both have pros and cons when it comes to Accessibility: https://www.upyoura11y.com/handling-form-errors/

**Comment by lookfirst** [comment]
Ok, I've hopefully cleaned this up. At least the demo feels right to me now. v2.1.0.

https://codesandbox.io/s/react-final-form-material-ui-example-4ftx9
