### ISSUE TITLE
Autocomplete initial value isn't displayed in the input field

### ISSUE THREAD

**Issue by ARTfun00** [lookfirst/mui-rff#169]
**Describe the bug**
Autocomplete initial values are not appear in the input field before direct user change

**To Reproduce**
1. Go to https://codesandbox.io/s/mui-rff-autocomplete-default-value-yb7zs to see example

**Expected behavior**
Initial values are displayed in the Input same as they displayed in the Debug helper

**Additional context**
Version: mui-rff 2.0.3

**Comment by lookfirst** [comment]
Thanks for the report, but you are doing it wrong. =)

Here is a working version of your code:

https://codesandbox.io/s/mui-rff-autocomplete-default-value-kr5lq
