### ISSUE TITLE
Add FormControl to Autocomplete

### ISSUE THREAD

**Issue by vitalii-dmytruk** [lookfirst/mui-rff#178]
**Is your feature request related to a problem? Please describe.**
Autocomplete isn't wrapped into a FormControl element. It forces us to deal with components in a non-consistent way. E.g. setting margins for Select is done by `formControlProps={{ margin: 'dense' }}`, but for Autocomplete I have to set it *manually*

**Describe the solution you'd like**
Wrap MuiAutocomplete into FormControl and pass properties via `formControlProps` as it is done with other Components

**Comment by lookfirst** [comment]
Hi there, 

Thanks for the issue.  As far as I can tell from the [demo site](https://lookfirst.github.io/mui-rff/), Autocomplete has a FormControl within it...

![image](https://user-images.githubusercontent.com/85355/78996678-effcf800-7af9-11ea-86c0-a103286e9410.png)

**Comment by vitalii-dmytruk** [comment]
You are right,
there is the one, which is created by MuiAutocomplete. 
It's tricky to find documentation on how to access its properties. But in case I pass some properties into Autocomplete's `textFieldProps` that are not suitable for MuiTextField, they go to the build-in MuiFormControl.
Anyway, I agree my issue is not an issue :) Sorry for the time you've spent.

**Comment by lookfirst** [comment]
@vitalii-dmytruk No worries at all! I do the same all the time.

Agreed, the documentation is a bit weak... I did [add a note](https://github.com/lookfirst/mui-rff#components) about that in the docs. Not sure if you noted that.

**Comment by vitalii-dmytruk** [comment]
My problem was not in the documentation of [mui-rff](https://github.com/lookfirst/mui-rff), but the Material UI.

It was hard for me to find out that Autocomplete uses FormContainer created by the build-in TextField component. 

So, I have no complaints about the documentation you wrote. At least for the part, I've read ;)  J

**Comment by lookfirst** [comment]
@vitalii-dmytruk Thanks for the clarification! 

Yes, I agree, several of their components are actually wrapper components (TextField is another prime example) and several are not. It made creating mui-rff a bit more difficult (along with some early bugs) as I had to figure a bunch of that stuff out myself! In the end though, that is part of why I like this library so much... I bring it all together into one easy to use component.
