### ISSUE TITLE
Autocomplete does not return error message on validation

### ISSUE THREAD

**Issue by leonardyrj** [lookfirst/mui-rff#188]
Autocomplete does not return error message on validation.

**Comment by lookfirst** [comment]
You're going to have to provide a bit more information there buster... this is in the demo app... you can see the error message...

![image](https://user-images.githubusercontent.com/85355/79534144-a303af00-802e-11ea-9936-31c7aea6ec1d.png)

**Comment by lookfirst** [comment]
Open for 9 days and no feedback, I'm going to close this one. Please comment and we can re-open it.
