### ISSUE TITLE
Reset not working?

### ISSUE THREAD

**Issue by dalmo3** [lookfirst/mui-rff#206]
**Describe the bug**
How to reset the fields to their initial values? I've played with both demo sandboxes and in neither case reset works.

I'm using vanilla js but with ts linting enabled. If I write just like the [another demo](https://codesandbox.io/s/react-final-form-material-ui-example-tqv09?file=/src/index.js:4523-4787F)
```javascript
              render={({ handleSubmit, reset, submitting, pristine, values }) => (
                 ...
                  <Button
                    type="button"
                    variant="contained"
                    onClick={reset}
                    disabled={submitting || pristine}
                  >
                    Reset
                  </Button>
```
My linter gives `Property 'reset' does not exist on type 'FormRenderProps<any>'.ts(2339)`

The [other demo sandbox](https://codesandbox.io/s/react-final-form-material-ui-example-xxspf?file=/src/index.tsx:9114-9118) has a convoluted way to implement `onReset` that only works after submitting, thus defeating the purpose.

**To Reproduce**
1. Go to any of the demo sandboxes
2. Edit stuff
3. Click reset
4. Data is not reset

**Expected behavior**
Fields should reset to initialValues, just like [it does in RFF](https://codesandbox.io/s/m40yyj2nyx?file=/index.js)

Sorry if this is not a bug (just move it to feature request then 😅).

**Comment by lookfirst** [comment]
Thanks for the issue! Heh, I never tried clicking reset in the demo before. You're totally right that it is broken.

Instead of `reset`, it should be `form` and `onClick={form.reset}`.

I just updated both examples, sorry for the confusion!

**Comment by dalmo3** [comment]
Thanks, worked great!
