### ISSUE TITLE
TextField hardcoded InputLabelProps={{ shrink: !!value }}

### ISSUE THREAD

**Issue by agraver** [lookfirst/mui-rff#21]
https://github.com/lookfirst/mui-rff/blob/6adb9c6bfdef0c4fb83d29e5f200452dfa9149fa/src/TextField.tsx#L37

**Describe the bug**
property `InputLabelProps` (as a consequence placeholder) has no effect on the input

```
<TextField
    ...
    placeholder="kek"
    InputLabelProps={{ shrink: true }}
/>
```
**To Reproduce**
expected:
https://codesandbox.io/embed/react-final-form-material-ui-example-yhnkt

current:
https://codesandbox.io/s/react-final-form-material-ui-example-0u0tg

**Comment by agraver** [comment]
https://github.com/lookfirst/mui-rff/blob/6adb9c6bfdef0c4fb83d29e5f200452dfa9149fa/src/TextField.tsx#L37

```
import React from 'react';

import { Field, FieldRenderProps } from 'react-final-form';
import { TextField as MuiTextField } from '@material-ui/core';
import { TextFieldProps as MuiTextFieldProps } from '@material-ui/core/TextField/TextField';

export function TextField(props: Partial<MuiTextFieldProps>) {
	const { name } = props;

	return (
		<Field
			name={name as any}
			render={({ input, meta }) => <TextFieldWrapper input={input} meta={meta} {...props} />}
		/>
	);
}

function TextFieldWrapper(props: FieldRenderProps<MuiTextFieldProps, HTMLInputElement>) {
	const {
		input: { name, onChange, value, ...restInput },
		meta,
		...rest
	} = props;

	const showError = ((meta.submitError && !meta.dirtySinceLastSubmit) || meta.error) && meta.touched;

	return (
		<MuiTextField
			fullWidth={true}
			helperText={showError ? meta.error || meta.submitError : undefined}
			onChange={onChange}
			name={name}
			value={value}
			margin="normal"
			error={showError}
			{...rest}
			InputLabelProps={{ shrink: !!value }}
			inputProps={restInput as any}
		/>
	);
}
```

**Comment by lookfirst** [comment]
@agraver Great feedback on both issues. Happy to get those fixed asap. Would you like to submit a PR or have me do the changes?

**Comment by lookfirst** [comment]
Ok, I think this has been fixed in v1.4.2. Let me know if I missed anything and we can reopen it easily.

**Comment by zacheryph** [comment]
Is there any specific reasoning for setting this? I have noticed this breaks Adornments as well. I have to do `InputLabelProps={{}}` to get startAdornment to work properly.

![Screen Shot 2019-12-31 at 10 45 26 AM](https://user-images.githubusercontent.com/476/71627899-e0951700-2bba-11ea-8a22-867ac0ba3dbb.png)

**Comment by lookfirst** [comment]
@zacheryph The reason is these two: 

https://material-ui.com/components/text-fields/#shrink
https://material-ui.com/components/text-fields/#floating-label

For me, the majority use case is with it enabled, so that is why I defaulted to true. But happy to consider changing it. What do you think?
