### ISSUE TITLE
Adornment doesn't appear on TextField

### ISSUE THREAD

**Issue by marr** [lookfirst/mui-rff#217]
**Describe the bug**
Adding an `endAdornment` prop to at `TextField` appears to have no effect.

**Expected behavior**
The `endAdornment` prop should behave as described in the TextField documentation. 
See https://material-ui.com/components/text-fields/#input-adornments

**Comment by marr** [comment]
I was using the wrong syntax. Needed to use `InputProps={{endAdornment}}` Sorry for the mistake!

**Comment by lookfirst** [comment]
@marr Glad you got it worked out. If you have any other questions, feel free to keep opening issues and closing them before I wake up. Ha! =)
