### ISSUE TITLE
Separate field errors from makeValidate()

### ISSUE THREAD

**Issue by johnmagbag1995** [lookfirst/mui-rff#225]
**Describe the bug**
makeValidate() returns field error in a single string.

**To Reproduce**
1. Go to 'https://codesandbox.io/s/react-final-form-material-ui-example-gl88m'
2. Type '2!' from test field
3. See field error

**Expected behavior**
makeValidate should return a list of field errors or display the first error only

**Screenshots**
Form Schema (This is just a test scenario)
![image](https://user-images.githubusercontent.com/61783659/82336335-06617200-9a1d-11ea-8276-24000049ad16.png)

Result:
![image](https://user-images.githubusercontent.com/61783659/82335832-6efc1f00-9a1c-11ea-85ea-66a21d66bc2c.png)

**Comment by lookfirst** [comment]
Thanks for the report!

What I'm thinking it that you should be able to pass in a transformation function that allows you to format the text however you want. What do you think of that?

**Comment by marr** [comment]
I just ran into this issue as well. Transformation function makes sense.

**Comment by lookfirst** [comment]
@marr Thanks for the feedback!

**Comment by johnmagbag1995** [comment]
@lookfirst Can you describe what kind of transformation function? I'm already using Yup matches on 30+ forms. Is it possible to put an option like **makeValidate(schema, true)**?

**Comment by vishalvijay** [comment]
I just faced this issue. 

<img width="612" alt="Screenshot 2020-06-01 at 10 03 22 AM" src="https://user-images.githubusercontent.com/2828848/83376234-2d418000-a3ef-11ea-8d04-afbc6d32299e.png">

As a library user's point of view, this looks broken.

@lookfirst I agree that we can use a transformation to solve this. But as this library is meant to be used along with Material-UI, most of the users will follow the same style for multiple validations messages.

So I would say this common issue has to be solved in this library in a generic way, by still giving support to transformation function.

**Comment by lookfirst** [comment]
> most of the users will follow the same style for multiple validations messages.

Show me an example. =)

**Comment by vishalvijay** [comment]
Sure. I'll get back with it.

**Comment by vishalvijay** [comment]
Sorry, got engaged with something else, hence the delay :)

<img width="639" alt="Screenshot 2020-06-09 at 12 38 57 PM" src="https://user-images.githubusercontent.com/2828848/84116922-5ba60780-aa4e-11ea-90cf-afe96af3f206.png">


I made it like this, using the `translator` function.

The code is something like this

```js
makeValidate(schema, (err) => {
  const { path, message } = err;

  return <span style={{ display: 'block' }} key={`${path}-${message}`}>{message}</span>;
})
```

* I was initially trying to use use `div` which thrown a warning because the error message is already wrapped in `p`
* `key` is required to avoid React error because it is an array of elements inside `p`

**Comment by lookfirst** [comment]
Closing, this is not an issue with mui-rff itself. Feel free to write your own makeValidate functions. =)
