### ISSUE TITLE
Autocomplete not displaying error without helperText

### ISSUE THREAD

**Issue by hanwiz** [lookfirst/mui-rff#257]
**Describe the bug**
Autocomplete without "helperText" cannot generate the error message.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-final-form-material-ui-example-gfblb
2. Click on SUBMIT
3. Autocomplete doesn't display the error while TextField just displays its error.

**Expected behavior**
Autocomplete should display the error.

**Comment by lookfirst** [comment]
Thanks for this. Autocomplete in general is just a messy component. It has been on my plate for a bit now to finish cleaning it up. =( I'll get there eventually... just life and covid (i don't have it) have kind of overloaded me at this point.

**Comment by lookfirst** [comment]
I updated to the latest version and this seems to be fixed now. Apologies for the issue and delay!

![image](https://user-images.githubusercontent.com/85355/89722815-f5ccf200-d9a2-11ea-926b-2b19bbeb4be4.png)
