### ISSUE TITLE
TypeScript compile error - showError does not exist 

### ISSUE THREAD

**Issue by maccuaa** [lookfirst/mui-rff#265]
**Describe the bug**

The new `showError` prop is missing from the TextField Props definition which is causing TSC compilation errors.

Note that this may be affecting other components as well but I didn't check them. 

**To Reproduce**

Add the `showError` prop to a TextField component in a TypeScript project.

Here is CodeSandbox project I made demonstrating the issue - https://codesandbox.io/s/mui-rff-showerror-7tiow

**Expected behavior**

No TSC errors when compiling.

**Comment by lookfirst** [comment]
That's annoying. I accepted a PR and I didn't pay close enough attention to it. It was really incomplete. =(

I've hopefully fixed this in 2.4.0. Thanks for the report.
