### ISSUE TITLE
Autocomplete does not show initial selected value

### ISSUE THREAD

**Issue by istinkevics** [lookfirst/mui-rff#273]
**Describe the bug**
Autocomplete does not show initial selected value since v2.2.0 (v2.1.15 works fine)

**To Reproduce**
1) Open demo page - [demo](https://lookfirst.github.io/mui-rff/)
2) Notice that initial values for autocomplete are: `"planet_one": "mars"` and `"planet": ["mars"]`
3) None of them are shown as "selected" in autocomplete box.

**Expected behavior**
I expect that initial value is selected.

**Screenshot**
[Issue screenshot](https://imgur.com/a/B7wRTSW)

**Additional context**
I guess this happened because of changes here: https://github.com/lookfirst/mui-rff/blob/4d03364b086065d0e47958e1c52dd47b406275c8/src/Autocomplete.tsx#L109-L110

**Comment by DASPRiD** [comment]
Any news on this? This makes the Autocomplete unusable right now.
