### ISSUE TITLE
Textfield issues with inputProps

### ISSUE THREAD

**Issue by johnmagbag1995** [lookfirst/mui-rff#285]
**Describe the bug**
Textfield validation errors are not showing if the field has inputProps

**To Reproduce**
1. Go to https://codesandbox.io/s/react-final-form-material-ui-example-forked-8fids?file=/src/index.jsx
2. Click on "Field with inputProps" field (leave it blank)
3. Click on "Field WITHOUT inputProps" field (leave it blank)
4. Click outside the form.
4. Both fields should have required validation error.

**Expected behavior**
![image](https://user-images.githubusercontent.com/61783659/91794761-730c1f80-ec4e-11ea-863e-262e8a7a6297.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/61783659/91794677-41935400-ec4e-11ea-839e-58a38d1ad22c.png)

**Comment by lookfirst** [comment]
Any suggestions on a fix?
