### ISSUE TITLE
Custom onChange handler

### ISSUE THREAD

**Issue by yourGuy** [lookfirst/mui-rff#286]
I might be missing something, but it seems it's not possible to create a custom onChange for a mui-rff TextField

**Comment by lookfirst** [comment]
Hi there, thanks for your comment. You are correct... this is handled with RFF. You would watch the data output of RFF.

I'm going to close this because it isn't an issue.

**Comment by yourGuy** [comment]
Not sure what you mean by "You would watch the data output of RFF" I would like a similar custom onChange handler like in our Autocomplete component 
Additionally there is a bug : if you pass onChange  to the TextField the field does not work (remains empty when you type)

**Comment by lookfirst** [comment]
Sorry, I was on my phone and in a rush. In most cases, onChange isn't necessary with RFF. I suspect your usecase is to do something like a conditional field where you hide/show content based on a selection. RFF has a great example for this:

https://codesandbox.io/s/lm4p3m92q

The onChange functionality added to the AutoComplete is something that I probably shouldn't have allowed in.

**Comment by yourGuy** [comment]
My use case is simple: I want to trigger an unrelated state change when a filed is changed, which I know how to do with a custom RFF Field implementation, however I'm here because of the convenience and declarativness of mui-rff and was hoping that when you pass onChange to mui-rff TextField it in turn does something like 
```
({input}) =>
<MuiField
onChange = {()=>
{
props.onChange();
input.onChange();
}
}
```

**Comment by lookfirst** [comment]
It is an interesting idea. I would say start with a PR and let's see what happens. It will require eventually changing all the other components to support this as well.
