### ISSUE TITLE
Autocomplete is changing the uncontrolled value state to be controlled.

### ISSUE THREAD

**Issue by igakim** [lookfirst/mui-rff#308]
**Describe the bug**
Autocomplete is changing the uncontrolled value state to be controlled when choosing option

**To Reproduce**
1. Go to [codesandbox](https://codesandbox.io/s/inspiring-dew-05nhv?file=/src/App.js)
2. Try choose any option
3. See console.

**Expected behavior**
Shouldn't change state

I think this is due to the fact that the `defaultValue` [remains](https://github.com/lookfirst/mui-rff/blob/master/src/Autocomplete.tsx#L105-L127) `undefined` if `getOption` was passed but value was not.

Maybe set to `null` by default, because from [react-final-form](https://final-form.org/docs/react-final-form/types/FieldProps#allownull):

> By default, if your value is null, <Field/> will convert it to '', to ensure controlled inputs

**Comment by lookfirst** [comment]
Slightly better codesandbox... 

https://codesandbox.io/s/magical-sid-8elrs?file=/src/App.js

Not sure the solution to this though. =(

**Comment by WendySclerandi** [comment]
Hi! Any updates on this? I have the same problem and I don't know how to fix it.

**Comment by lookfirst** [comment]
Hi @WendySclerandi, play around with #309 and see what you get... I'm not super happy with the code there because it isn't super TS happy... I've been waiting to see if anyone else comes along and does a better job. I shouldn't be the only person on this project that knows TS. ;-)

**Comment by deepak-evry** [comment]
Any workaround for this?

**Comment by benoit-nadaud** [comment]
Anybody found a solution for this ?

**Comment by Gryndii** [comment]
same error, somebody found how to fix it?

**Comment by Gryndii** [comment]
Ok guys
In my case for 'multiple=true' Autocomplete helped this:
1. If you fetch options - do not render Autocomplete until you have completed loading options.
2. Set initial form value for this field as '[ ]'.

 🤯

**Comment by lookfirst** [comment]
@Gryndii This is noted in the documentation:

`When multiple is true, the initialValues passed into the <Form> element needs to be an array...`

**Comment by Gryndii** [comment]
@lookfirst my bad. But now got same error for non multiple autocomplete( Any ideas how to fix that?

**Comment by lookfirst** [comment]
@Gryndii I wonder if there is any correlation with #739

**Comment by lookfirst** [comment]
Closing, seems to be a non issue now?

**Comment by lookfirst** [comment]
@Lucas-Alf Thanks for the update. I've reopened for now until myself or someone else can find the time to investigate this further.

**Comment by Rassilion** [comment]
Looks like setting `null` fixes problem.

changing this to 
https://github.com/lookfirst/mui-rff/blob/646a5393705093508fad8acedecbdda11584d0b7/src/Autocomplete.tsx#L150

```ts
value={defaultValue ?? null} 
```

fixes problem. 

But mui types doesn't like `null` value, but in the [docs ](https://mui.com/material-ui/react-autocomplete/#controlled-states) look like it can be `null` (on clear value). Maybe a type change needed on mui side.

**Comment by lookfirst** [comment]
Thanks for the input @Rassilion.

autocomplete.value can be a value or undefined.

`defaultValue` is something generated within mui-rff with some overly complicated boolean logic that at some point, isn't defining undefined, when it probably should be.

**Comment by Lucas-Alf** [comment]
Just an observation.
Is this **defaultValue** logic not running on every render?
Isn't it better to put this inside the **onChangeFunc** function?

**Comment by lookfirst** [comment]
The defaultValue logic is complicated because we can specify the list of options programmatically through `getOptionValue()`. Optimizing the render could be considered, but let's get the base logic correct to begin with. =)

This complicated internal stuff is exactly why mui-rff exists... everyone would have to implement this themselves...

**Comment by Rassilion** [comment]
To clarify my main issue is different but looks like connected to this issue.

My problem is on server fetching `options`  on forms with `initialValues`. On initial render `options` is empty array after api call `autocomplete` with `initialValues` should have visible value but they look like empty inputs. `autocomplete` should rerender when `options` changed but probably because it's in uncontrolled state (value==undefined) it is not reacting  `options` change.

basic example in codesandbox; on initial render input looks doesn't have a value but after `hide/show` button clicked input shows it's `initialValues` correctly.
https://codesandbox.io/s/cold-brook-dif96u?file=/src/App.js

**Comment by lookfirst** [comment]
Great example. I can see pretty clearly the uncontrolled shit. I have zero idea on how to fix it all though. =(

**Comment by lookfirst** [comment]
Oh, just a thought on the example. Try putting the data fetching into a useEffect()... so when the component first loads, it is initialValues of undefined, and then when the data loads, the component will re-render and be populated.

**Comment by lookfirst** [comment]
Geez, I'm at a loss.

**Comment by Rassilion** [comment]
Mui says
>The nature of the state is determined during the first render. It's considered controlled if the value is not `undefined`.

Final Form says
>By default, if your value is null, [<Field/>](https://final-form.org/docs/react-final-form/api/Field) will convert it to '', to ensure [controlled inputs](https://reactjs.org/docs/forms.html#controlled-components).

`defaultValue` being `undefined` creates uncontrolled state, setting it to `null` fixes my case in Single select but  didn't tested on multiple and freesolo selects.

Maybe somethinmg like this fixes all cases. Like [mui type](https://github.com/mui/material-ui/blob/00a0d5863e67a0da69f9ed9b6ea074b4950afcc2/packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.d.ts#L30) if `defaultValue` is `undefined` on single and multiple select set it to `null`, on multiple select set it to `[]` and if `disableClearable` given let it be `undefined`

**Comment by kjellski** [comment]
This is still a problem - `defaultValue` stays `undefined` when `getOptionValue` was passed. I would like to contribute a fix PR for this, with added test, but unfortunately I am unable to run the test suite: 

```
 FAIL  test/Autocomplete.test.tsx
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'testEnvironmentOptions')
```

**Comment by kjellski** [comment]
Yes, this can be merged, needs to be released in a new version though...

**Comment by lookfirst** [comment]
Yea, I'll try to get that out today! =)
