### ISSUE TITLE
[Feature] Checkboxes: allow indeterminate flag to be supplied to each checkbox option

### ISSUE THREAD

**Issue by mbyrne00** [lookfirst/mui-rff#321]
**Is your feature request related to a problem? Please describe.**
Material checkbox allows `indeterminate` flag to mark individual options as indeterminate (e.g. when you want "Not applicable" to not appear as an option if you select others). Currently the `Checkboxes` API only allows this boolean to be supplied once for all items.

**Describe the solution you'd like**
`CheckboxData` to have an optional `indeterminate` field of type `boolean` for each item.

**Describe alternatives you've considered**
Since this flag generally needs to change based on the values of the field it may be a nicer option to allow for a function to define any additional properties per individual `Checkbox` to be returned. In this case I want to set/unset the `indeterminate` flag based on the current field value(s) ... allowing any other additional properties may future proof this wrapper for other options.

**Comment by lookfirst** [comment]
Hi @mbyrne00 ! Thanks for the issue.

Sure, this shouldn't be a hard change. All that needs to happen is:

interface CheckboxData (add):
indeterminate?: boolean

https://github.com/lookfirst/mui-rff/blob/master/src/Checkboxes.tsx#L84
indeterminate={item.indeterminate}

and the appropriate tests added of course.

Would you like to take a stab at it?

I'm not against it, but I'd like to see the above done first and then a separate PR for your alternative just to keep things simple.

**Comment by mbyrne00** [comment]
Sure - I need to play with it in my codebase to get a feature across first and that will serve as a good test of the feature to see what works.

**Comment by lookfirst** [comment]
The best test is writing tests. ;-)

**Comment by mbyrne00** [comment]
Indeed :) ... I mean the "how", not the "what" .... what I want to get out of this feature. Callback vs prop value etc due to the changing nature of `indeterminate` based on other values.

**Comment by lookfirst** [comment]
I would think that you’re just building the values of the component and
rendering it. A callback is therefore unnecessary since it would just be
another render.

**Comment by mbyrne00** [comment]
Yea - thought about that after ... agreed.

**Comment by mbyrne00** [comment]
Hi - apologies for not getting to this. We didn't end up needing this feature and I got pulled onto another urgent project. Having said that I'd still like to contribute, so I've let the team know to spare me some time this week.

**Comment by lookfirst** [comment]
@mbyrne00 No worries, we are all busy. =)
