### ISSUE TITLE
KeyboardDateTimePicker does not displays initalValues

### ISSUE THREAD

**Issue by MilanKosticKIT** [lookfirst/mui-rff#342]
The KeyboardDateTimePicker does not show the inital Values on Safari/mobileSafari. Furthermore the, by keyboard, entered values are not formatted and TypeErrors are shown in the console:
![grafik](https://user-images.githubusercontent.com/19825071/98705501-12037500-237e-11eb-81d8-ccbd375638c4.png)
Values entered using the GUI are correctly handeled.
The Code does work fine when instead of KeyboardDateTimePicker the DateTimePicker is used.
Under Firefox and Chromium both components work just as intended.

```
<Form
          initialValues={initialValues}
          onSubmit={createNewEntry}
          render={({handleSubmit, values}) => (
            <form onSubmit={handleSubmit} id="modalForm" noValidate>
                <KeyboardDateTimePicker
                  required
                  variant="inline"
                  ampm={false}
                  label="KeyboardDateTimePicker"
                  name="time"
                  fullWidth
                  format="dd.MM.yyyy HH:mm"
                />
          </form>
            )}
        />
```

**Expected behavior**

**Desktop:**
 - macOS 10.13.6
 - Safari 13.1.2

**Smartphone:**
 - iPhone X
 - iOS 14.0.1
 - Safari

**Comment by lookfirst** [comment]
Thanks for the report. Is this something specific to MUI or the underlying component itself?

**Comment by MilanKosticKIT** [comment]
This behaviour poped up just after changing from MUI to MUI-RFF component.

**Comment by lookfirst** [comment]
Same version? I'd really need to see a codesandbox.

**Comment by MilanKosticKIT** [comment]
Well my own Sandbox has some other issues currently . <br>Though in the example Sandbox the part of the problem that the input won't be parsed correctly is visible (this time in firefox too):
https://codesandbox.io/s/react-final-form-material-ui-example-xxspf

**Comment by lookfirst** [comment]
I'm sorry, but you're going to have to give me something that I can easily test. Pare it down to just the bare minimums please.

**Comment by lookfirst** [comment]
Closing, this no longer exists.
