### ISSUE TITLE
[feature] autocomplete

### ISSUE THREAD

**Issue by TrejGun** [lookfirst/mui-rff#36]
please add bindings to autocomplete
you can use my article as example
https://trejgun.github.io/articles/bindings-for-using-final-form-with-material-ui-autocomplete

**Comment by lookfirst** [comment]
@TrejGun Would you like to submit a PR and let's get working on it? I would change a couple small things in your coding style, but other than that, it looks very good. I would also want you to include tests too.

Strangely, clicking on the link above doesn't work, gives me a 404 ... I'm going to include it here as a test...

https://trejgun.github.io/articles/bindings-for-using-final-form-with-material-ui-autocomplete

**Comment by TrejGun** [comment]
I would like but will not have time  untill 20th of december

**Comment by lookfirst** [comment]
No problem. We can leave this open until we both have some time or the need comes up. =)

**Comment by aaronhayes** [comment]
I've implemented a stopgap solution for myself. Not quite ready for a PR. but maybe this gist helps out:  https://gist.github.com/aaronhayes/a38d87f846b9a3041c391b3842e65b1a

My requirements were around async searching and selecting a single item. Haven't tested if `multiple` was working. 

If I can find some time I'll cleanup and make a PR.

**Comment by lookfirst** [comment]
@aaronhayes Thanks very much! Your code looks very solid.

**Comment by lookfirst** [comment]
@aaronhayes Just a quick update before I head to sleep... I took a first stab at this and I'm not happy with my results around the interfaces... I was trying to re-use the TextFieldWrapper... but I'm having trouble sorting out all the typescript types for all the properties... I'll try again tomorrow to see what I can figure out.

**Comment by aaronhayes** [comment]
@lookfirst I found the biggest problem with trying to reuse the `TextFieldWrapper` component is the `onChange` function is bound to the `TextField` whereas it needs to be attached to the `MuiAutocomplete` component. We need a way to pass an `onChange` event handler onto the `TextField` to capture input changes to trigger async searches.

**Comment by brandontruong-asx** [comment]
hi @aaronhayes , I think you need to add  getOptionLabel: (option: any) => any; as part of the prop, otherwise it will cause error. Something like

interface AutocompleteProps extends Partial<MuiAutocompleteProps> {
  name: string;
  label: string;
  getOptionValue: (option: any) => any;
  **getOptionLabel: (option: any) => any;**
  options: AutocompleteOption[];
  required?: boolean;
  fieldProps?: FieldProps<any, any>;
  textFieldProps?: Partial<MuiTextFieldProps>;
}

**Comment by aaronhayes** [comment]
@brandontruong-asx 
Don't need to declare it specifically as we extend `MuiAutocompleteProps`. `getOptionLabel` gets passed to `MuiAutocomplete` using `...rest` .

```TypeScript
import {
  default as MuiAutocomplete,
  AutocompleteProps as MuiAutocompleteProps
} from '@material-ui/lab/Autocomplete';

interface AutocompleteProps extends Partial<MuiAutocompleteProps> {
  name: string;
  label: string;
  getOptionValue: (option: any) => any;
  options: AutocompleteOption[];
  required?: boolean;
  fieldProps?: FieldProps<any, any>;
  textFieldProps?: Partial<MuiTextFieldProps>;
}
```

**Comment by aaronhayes** [comment]
This at least works for me ... you're result may vary 😆

**Comment by naveennsit** [comment]
any body answer this https://stackoverflow.com/questions/59832331/why-checkbox-is-not-checked-in-react?noredirect=1#comment105801358_59832331

**Comment by aaronhayes** [comment]
Draft PR: https://github.com/lookfirst/mui-rff/pull/89

**Comment by lookfirst** [comment]
This is published as 1.7.0 now.

**Comment by lookfirst** [comment]
Huge round of thanks to @aaronhayes for doing a great job here!

**Comment by TrejGun** [comment]
thanks!
