### ISSUE TITLE
Select trigger error when using both MenuItem(s) and mapping over array

### ISSUE THREAD

**Issue by jhammersholt** [lookfirst/mui-rff#367]
**Describe the bug**
Combining MenuItem component and mapping over variable triggers tslint error when using Select component

**To Reproduce**
```
    <Select name="test">
      <MenuItem value={-1}>Option #1</MenuItem>
      {options.map((o) => (
        <MenuItem value={o.id} key={o.id}>
          {o.name}
        </MenuItem>
      ))}
    </Select>
```

which gives me this error
> Type 'Element[]' is missing the following properties from type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)>': type, props, keyts(2739)

**Expected behavior**
I expected to not get an error (i get none if i use TextField component set to select or if i use Select directly from material-ui

**Additional context**
doing this work, but it feels wrong
```
    <Select name="test">
      {[
        <MenuItem value={-1}>Option #1</MenuItem>,
        ...options.map((c) => (
          <MenuItem value={o.id} key={o.id}>
            {0.name}
          </MenuItem>
        )),
      ]}
    </Select>
```

**Comment by lookfirst** [comment]
Hi there, thanks for the bug report. The problem isn't in this library, it is in your options.

```
  const options = [
    {
      id: '1',
      name: '1',
    },
  ] as any;
```

Just add `as any` at the end (or setup the right object that is expected per the error message from tslint).

**Comment by lookfirst** [comment]
![image](https://user-images.githubusercontent.com/85355/102721119-a9c57e80-42ad-11eb-90e6-3462c8a923ec.png)

![image](https://user-images.githubusercontent.com/85355/102721128-ba75f480-42ad-11eb-8044-4bd9d354cfce.png)

**Comment by jhammersholt** [comment]
as any really shouldn't be an option, it pretty much defeats the purpose of Typescript imo

That being said you did notice its working as intended with your Textfield component as well as both Select and Textfield directly from material-ui

You mention "setup the right object that is expected per the error message from tslint" could you point me in the direction to discovering said types?

**Comment by lookfirst** [comment]
At some point with TS, I give up on having perfect types, that is one of them.

But, you have a good point... I went back to look at what MUI declares for a type there and they use a ReactNode for children of Select. So, I've done a new release with this (3.0.2). Let me know if it helps you.

**Comment by lookfirst** [comment]
Ok, tested on codesandbox and seems to work now.

![image](https://user-images.githubusercontent.com/85355/102724002-0d0cdc00-42c1-11eb-9f8e-7ee607005065.png)

**Comment by lookfirst** [comment]
Thanks and apologies for not 'getting it' at first. =)

**Comment by jhammersholt** [comment]
> Thanks and apologies for not 'getting it' at first. =)

Thanks, works for me as well :)
