### ISSUE TITLE
freeSolo Autocomplete not working with SpyForm

### ISSUE THREAD

**Issue by slash-dev** [lookfirst/mui-rff#375]
**Describe the bug**
When using SpyForm and freeSolo autocomplete, the changes are only caught if I press enter or if I select one of the options.

**To Reproduce**
1. Go to 'https://codesandbox.io/s/react-final-form-auto-save-with-debounce-forked-2gkw0?file=/index.js'
2. Change the "Simple Text" field and see that it triggers a saving in the console logs on every value change.
3. Do the same with the "autocomplete" field and it only triggers when we select a value or press "Enter" after the change.

**Expected behavior**
We should be able to catch all the key strokes in the SpyForm in order to be able to save if any change is done.

**Desktop (please complete the following information):**
 - OS: Debian
 - Browser Chrome
 - Version 87.0.4280.88

**Additional context**

* I suspect this might be related to the onChange not working. I tried to set my own onChange and it looks like it didn't get called.
* It looks like the onSelect would get called after each key stroke THOUGH, interestingly, it doesn't when a I erase a character.
* Only when I type new ones.
* Even if the onSelect would work for all key strokes, I'm not sure how to pipe the event back to the SpyForm component.

Thank you!

**Comment by lookfirst** [comment]
Hi there, thanks for this issue. There is a number of autocomplete issues open in this project already and some of them may overlap with the issues you're seeing. You might have to investigate into that. Your help on this matter is appreciated.

**Comment by lookfirst** [comment]
Hi there, no responses since submission. I'm going to assume that this is either fixed or you moved on. If you'd like me to reopen, let me know.
