### ISSUE TITLE
Cannot set the default helperText for Select components in theme

### ISSUE THREAD

**Issue by nmay231** [lookfirst/mui-rff#428]
**Describe the bug**
Of course, vanilla mui Select elements do not have `helperText`; you have to add a `FormHelperText` to your form control with the helper text as a child. But setting `props.MuiFormHelperText.children='default helper text'` in my theme only changes the helper text for vanilla `FormHelperText`s.

This is necessary because I want to set the helper text to a space `' '` to prevent form resizing, e.g. when a field has error helper text.

**To Reproduce**
1. Go to [this forked sandbox](https://codesandbox.io/s/react-final-form-material-ui-example-forked-4e53v?file=/src/index.tsx:7030-7066)
2. Search for the comment: `// HERE: Try commenting the following line. The helper text`
3. ... And comment the following line :)

The additions I made are roughly...

```tsx
import {
  // ...
  FormControl,
  InputLabel,
  Select as MuiSelect,
  MenuItem,
} from '@material-ui/core'

// ...

const theme = createMuiTheme({
  props: {
    // ...
    MuiFormHelperText: {
      children: 'This should be the default helper text of all Select components',
    },
})

// ...

// In the render function of MainForm
  const formFields = [
    // Default helper text doesn't work here
    <Select
      label="Pick some cities..."
      name="cities"
      required={required.cities}
      data={selectData}
      multiple={true}
      // HERE: Try commenting the following line. The helper text
      helperText="Woah helper text"
    />,
    // Default helper text works here
    <FormControl>
      <InputLabel id="demo">Cities</InputLabel>
      <MuiSelect labelId="demo" fullWidth>
        {selectData.map(({ label, value }) => (
          <MenuItem value={value}>{label}</MenuItem>
        ))}
      </MuiSelect>
      <FormHelperText>{/* Insert helper text here */}</FormHelperText>
    </FormControl>,
  ];
```

I also removed most of the form components to simplify the example.

**Expected behavior**
Commenting out the line indicated should change the select helperText to `'This should be the default helper text of all Select components'`.

**Additional context**
This 'bug' is not a super high priority, but it would help with theming.

**Comment by lookfirst** [comment]
Hey! Thanks for the issue. I didn't even know that using children like that was a feature of MUI themes. =)

My guess is that there is some rendering order issue such that the theme gets applied before MUIRFF then renders the component and overwrites the value again. I have no idea how to fix this. =(

**Comment by lookfirst** [comment]
Oh wait, I think that I know the 'issue'...

https://github.com/lookfirst/mui-rff/blob/master/src/Util.tsx#L13

The `<FormHelperText/>` element is only rendered if there is a value for it and I bet that since this is coming from the theme, it isn't getting picked up from my code.

**Comment by nmay231** [comment]
@lookfirst I don't know if it's a "standard" feature, but `children` is a prop like any other and it works :shrug: 

So maybe converting that function to a simple if-else (aka, remove the last else) would work so that it can always render a FormHelperText?

**Comment by lookfirst** [comment]
I think the problem with always rendering it is that it takes up space by default.

**Comment by nmay231** [comment]
@lookfirst Hmm... There might be a small indiscernible difference. But I do know you have to use a space (`children=' '`) in order to reserve space for later ([docs](https://material-ui.com/api/form-helper-text/#props)).

When I have a more convenient moment, maybe I can set up a quick example to test that more thoroughly.

**Comment by lookfirst** [comment]
Yea, I noticed that in the docs. If you don't mind testing things out and seeing what happens, I'd appreciate the help greatly! =)

**Comment by nmay231** [comment]
@lookfirst Yeah, there is a margin-top of 3. Arg!

TBH, I have no idea how theming works in mui. Maybe it would be easy-ish to hook into mui themes and only render helper text if the theme provides a value? Unless you don't think a margin of 3 is that big of a deal.
<br/>

![1](https://user-images.githubusercontent.com/35386821/112270034-c66faa80-8c3e-11eb-9296-eeccb66ed405.png)
![2](https://user-images.githubusercontent.com/35386821/112270037-c7084100-8c3e-11eb-9deb-c7ea36f63716.png)

**Comment by nmay231** [comment]
[Example repo](https://github.com/nmay231/mui-helper-text)
