### ISSUE TITLE
[feature] Extend MUI components instead of wrapping them

### ISSUE THREAD

**Issue by lookfirst** [lookfirst/mui-rff#45]
Saving this here for discussion for anyone to pick up.

Per the suggestion here by @ornellast :

https://github.com/lookfirst/mui-rff/pull/31#issuecomment-557486469

> Why Checkboxes and Radios instead of a thin wrapper in their counterparts (Checkbox and Radio)?
> It's up to you decide, but I think you should create the wrappers keeping MUI interfaces, i.e., label should be a ReactNode instead string, or this library should 'extends' the MUI components rather than create new ones. It doesn't mean this library must not create new components (like the utility/shortcut to create multiple checkboxes and radios, they are very nice and useful); I think the focus should be to wrap the MUI components.
> 

Consider extending the MUI components, instead of wrapping them. I'd love to see an experimentation done as a PR on a branch. I don't have the time myself to work on this, but it is an interesting idea for sure!

**Comment by dantman** [comment]
I agree. I'm currently trying to port an already existing MUI form to final form. And my choices are now writing custom components, using an unmaintained library, or reverse engineering how this library's extended components work to figure out how to convert my FormControlLabel+Checkbox to the Checkboxes component.

**Comment by lookfirst** [comment]
@dantman Thanks for the comment. Sadly, this might not solve that specific issue for you. The problem is that MUI doesn't have a single component for Checkbox... it is a conglomeration of a total of 5 components. This library only uses the MUI recommended way of combining the components together.

Therefore, if your existing code followed the MUI patterns, this project should just be a drop in replacement for you. Of course, you can always override all the properties too (if not and I missed something, please file an issue please).

Ignore that unmaintained project, this one very much replaces it.

**Comment by lookfirst** [comment]
I'm going to close this one. The label issue has been fixed and I'm happy with the way the components are written at this point. The code is efficient and easy enough to read as it is and I don't see any benefits to changing things now. If there is something else specific that should be done, please feel free to open a new issue!
