### ISSUE TITLE
The Autocomplete component incorrectly passes the InputProps of the textFieldProps object.

### ISSUE THREAD

**Issue by samantagavare** [lookfirst/mui-rff#455]
**Describe the bug**
Version : 3.0.6
OS: Windows 10
Browser: Chrome 90.0.4430.93

The autocomplete InputProps parameter is completely overridden by the passed value, and after that Chips are no longer displayed. 
[Other](https://material-ui.com/api/text-field/) object type parameters of the TextField can also be affected: classes, FormHelperTextProps, InputLabelProps, and so on.

**To Reproduce**
* Open Sandbox [link](https://codesandbox.io/embed/react-final-form-material-ui-example-forked-clbif?).
* Start typing in the Autocomplete field and press enter.

**Expected behavior**
Chips and tooltip are displayed. 

**Actual behavior**
The tooltip is displayed, but the chips are not.

**Workaround**
* Copy the content of the [Autocomplete.tsx](https://github.com/lookfirst/mui-rff/blob/master/src/Autocomplete.tsx) file to a new file in your project.
* Add this:
`InputProps={{
						...params.InputProps,
						...restTextFieldProps.InputProps
					}}`
after
https://github.com/lookfirst/mui-rff/blob/0ba99ae24af40cd810bbe79d31cf2c4062c34009/src/Autocomplete.tsx#L167

**Comment by lookfirst** [comment]
Thanks for this. Do you want to submit a PR?

**Comment by samantagavare** [comment]
Yeah, sure. I will also try to include tests.

**Comment by lookfirst** [comment]
> Yeah, sure. I will also try to include tests.

Fantastic, I'll look forward to it!

**Comment by lmcculley** [comment]
This also fixes an issue where passing `disabled={true}` to the autocomplete would not disable the input.
https://github.com/lookfirst/mui-rff/pull/466

**Comment by lookfirst** [comment]
Released 3.0.7
