### ISSUE TITLE
Tree shaking of mui-rff does not work

### ISSUE THREAD

**Issue by dantman** [lookfirst/mui-rff#50]
**Describe the bug**
mui-rff's dist bundles do not support tree shaking. As a result even though I don't use any date pickers anywhere, the page I use a final form on has the entirety of the `@material-ui/pickers` library included in the production bundle.

**To Reproduce**
Use `webpack-bundle-analyzer` and build a production bundle of a project that uses mui-rff's TextField.

**Expected behavior**
Code from unnecessary modules should not be included in production bundles. And `@material-ui/pickers` especially should not be bundled when it's not used.

**Screenshots**
<img width="384" alt="Screen Shot 2019-12-06 at 5 17 43 PM" src="https://user-images.githubusercontent.com/53399/70366469-61772200-184c-11ea-95ec-554959ea416f.png">

**Additional context**
Including `"sideEffects": false,` in the package.json like `@material-ui/pickers` does.

Another may be to not bundle everything into a single file and allow for direct imports just like `@material-ui/core` does.

**Comment by lookfirst** [comment]
Agreed, that is ugly. So sad that tsdx doesn't handle this cleanly for me or maybe I'm just using it wrong. 

Hmm... I think you're right that the best way is to just allow the direct imports.

**Comment by lookfirst** [comment]
Added sideEffects: false in 1.5.3 per your request. Please let me know if this resolves it for you.

**Comment by TeChn4K** [comment]
Did someone success to configure Webpack tree shaking with mui-rff ?
