### ISSUE TITLE
Lib fails to install latest version

### ISSUE THREAD

**Issue by aloeugene** [lookfirst/mui-rff#525]
**Describe the bug**
When I try to simply install all dependencies in my repo with `yarn` – it fails because of `mui-rff`.

```sh
error /Users/~censored~/frontend-common/node_modules/mui-rff: Command failed.
Exit code: 1
Command: yarn run patch-package
Arguments:
Directory: /Users/~censored~/frontend-common/node_modules/mui-rff
Output:
```

**To Reproduce**
1. Go to any repo with `mui-rff` in package.json
2. Try run `yarn` to install all deps
3. See an error above

**Expected behavior**
I expect it to not fail any of my `yarn` installs because it blocks me from working right now 😢 

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.2.3

**Comment by Jayanth-Conjonction** [comment]
I have the same issue.

**Comment by lookfirst** [comment]
Fixed!

**Comment by aloeugene** [comment]
Thanks @lookfirst! I've tried upgrading to 3.0.13 and it finally works fine with no issues installing this package.

**Comment by lookfirst** [comment]
sorry about that!
