### ISSUE TITLE
Password field with type switch icon button

### ISSUE THREAD

**Issue by adsee42** [lookfirst/mui-rff#526]
**Is your feature request related to a problem? Please describe.**
AFAIK, this is a very common feature and recommended design style.
![image](https://user-images.githubusercontent.com/54787881/130046949-a64274fe-50b9-455b-be86-6570db504432.png)
![image](https://user-images.githubusercontent.com/54787881/130046978-4b46e561-5966-41a4-a67c-a8473da934d2.png)
We can easily implement this by ourselves, but all those `propTypes` or type definitions seems redundant and error-prone.

It would be nice to have a built-in `PasswordField` to save everyone's time and make life easier.

**Comment by lookfirst** [comment]
Sounds like a great suggestion.

**Comment by Gaurav4604** [comment]
Hello @lookfirst, I am new to the open source community and would like to contribute towards this issue, can you please tell me if this still serves as an enhancement towards this repo? Thanks 😁

**Comment by lookfirst** [comment]
@Gaurav4604 welcome to the open source community, we are happy to have you here. Adding this into mui-rff would be most appreciated.

**Comment by Gaurav4604** [comment]
@lookfirst, can you please walk me through some steps I would have to take for contributing?
(I am so sorry for bothering you with such basic things)

**Comment by lookfirst** [comment]
@Gaurav4604 I'm sorry, I just don't have time for that right now. =( I'm going to close this short of someone submitting a PR.
