### ISSUE TITLE
Allow Usage of Date Pickers Provider

### ISSUE THREAD

**Issue by zacheryph** [lookfirst/mui-rff#54]
**Is your feature request related to a problem? Please describe.**
I do not know how new it is, though the current `@material-ui/pickers` providers a `MuiPickersUtilsProvider` for retrieving the date Utils via context. This doesn't seem the be supported with the current `mui-rff`

**Describe the solution you'd like**
Allow `dateFunsUtils` attribute to be optional providing there is a `MuiPickersUtilsProvider` available as a parent.

**Describe alternatives you've considered**
_N/A_

**Additional context**
_N/A_

**Comment by lookfirst** [comment]
Hi @zacheryph ... thanks for the report!  

Sure, making dateFunsUtils optional is totally within reason.

Would you like me to make the change or would you like to try submitting a PR for it? Either way is fine. =)

**Comment by zacheryph** [comment]
@lookfirst Let me take a stab at it over the next couple days. Is there any reason to not just make people aware they must add the Picker Provider over allowing them to include `dateFunsUtils` ? or, just re-export it? Given the way its not a dependency we are requiring the user be aware of this dependency in the first place?

**Comment by lookfirst** [comment]
Personally? I think the Picker Provider takes the provider pattern a bit too far into magic lala land of providers for the sake of providers.

The problem being that it would be easy to: a) include the provider element too many times, by accident, in a deeply nested project which leads to receiving an error and then having to fix it. b) it is overkill when this is just an attribute which takes an imported thing.

What if I don't put the provider high enough up in the layout dom tree? What if I put it around the body of the page, but not the header and now I want to put a date in the header?

I personally try to keep providers for things that require some sort of initialization or used all through the codebase in a context-like object. Just exposing an import to JSX doesn't seem logical.

So yea... while I won't use this provider personally... I do still want to support it. So both methods seem appropriate.

=)

**Comment by zacheryph** [comment]
haha. I can agree, I think it's an odd place to be using Provider.

I will see what I can do.

**Comment by lookfirst** [comment]
This is being tracked in PR #57 so I'm going to close it here. Hope that is ok.
