### ISSUE TITLE
Autocomplete isOptionEqualToValue is not recognize

### ISSUE THREAD

**Issue by BrandonBx** [lookfirst/mui-rff#562]
**Describe the bug**
According to the documentation of MUI, the autocomplete should have a prop "isOptionEqualToValue". The browser doesn't recognize it when I import Autocomplete from mui-rff

**Expected behavior**
mui-rff has to implement this recent option.

**Screenshots**
![image](https://user-images.githubusercontent.com/25326576/135916691-e42e0243-577a-4bab-9f52-00f0117f523f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version : last

**Comment by lookfirst** [comment]
Thanks for the report, that is a MUI 5.x option and we are still at 4.x. You'll have to wait for us to upgrade to 5 (or help us!)
