### ISSUE TITLE
All Checkboxes re-render when one is selected

### ISSUE THREAD

**Issue by zamgill** [lookfirst/mui-rff#576]
**Describe the bug**
When using Checkboxes with ReactNode for labels. All labels re-render when on when a checkbox is selected.

**Expected behavior**
Only the checked checkbox should re-render.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Edge
 - Version 94.0.992.50

**Comment by lookfirst** [comment]
@zamgill Cool. Highly suggest that you learn to write tests. It will save you more time than not.
