### ISSUE TITLE
Date Parsing Funniness

### ISSUE THREAD

**Issue by zacheryph** [lookfirst/mui-rff#58]
**Describe the bug**
I think this really belongs to `@date-io` or `date-fns`, or even `@material-ui/pickers` 😕.  I looked through tickets quickly but didn't see anything that popped out. I am getting previous dates for actual values. DatePicker and KeyboardDatePicker fail trying to find `2014-08-17` vs the hardcoded value `2014-08-18`.

**To Reproduce**
1. uhh...
2. System TZ is CST
3. Open Examples
4. View screenshot below

**Expected behavior**
`2014-08-18` to be `2014-08-18` 😄 

**Screenshots**
Notice the form field data on the right for `birthday` and what it is on the picker itself.

![Screen Shot 2019-12-16 at 11 17 43 AM](https://user-images.githubusercontent.com/476/70928349-7bf08e80-1ff6-11ea-9a85-4d0810b7da59.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 79.0.3945.79

**Additional context**
I see this same issue in `material-table` when filtering on a column specified as `type: "date"`. This is also using `@date-io/date-fns` / `date-fns`

**Comment by zacheryph** [comment]
I think this is related to: https://github.com/date-fns/date-fns/issues/376

**Comment by zacheryph** [comment]
Tests run perfectly fine when I do `env TZ=UTC yarn test`. This is a known three year old issue with `date-fns` 😢  Not sure this could be something enforced in `scripts` or in code itself or otherwise.

**Comment by kossnocorp** [comment]
@zacheryph it's not a date-fns issue but rather a `Date` parsing quirk, and I recommend to use `parseISO` to avoid the problem. See my comment: https://github.com/date-fns/date-fns/issues/376#issuecomment-566368258

**Comment by lookfirst** [comment]
Oh funny, I saw this as well before while developing the library. Then it magically went away, so I shrugged it off.

@zacheryph Can we close here since this isn't related to mui-rff?
