### ISSUE TITLE
Error message is not shown for a single checkbox

### ISSUE THREAD

**Issue by sgarcialaguna** [lookfirst/mui-rff#70]
**Describe the bug**
When you a single required checkbox and try to submit the form without checking it, no error is shown. This works fine for multiple checkboxes

**To Reproduce**
1. Go to https://codesandbox.io/s/react-final-form-material-ui-example-d8leo. I have forked the example sandbox from the readme, so it should look familiar.
2. Click on Submit
3. An error is shown for the group of checkboxes, but not for the single checkboxes

**Expected behavior**
Error should be shown for single checkboxes as well.

**Comment by lookfirst** [comment]
@sgarcialaguna Thank you for the report! You are correct that this is an issue. I will do some research and work on a solution, expect something soon.

One thing I did notice though is that your example wouldn't work either way... =)

![image](https://user-images.githubusercontent.com/85355/71775929-07888a00-2fbb-11ea-9b82-b62022e4b3ad.png)

**Comment by sgarcialaguna** [comment]
Haha, fixed.

**Comment by lookfirst** [comment]
@sgarcialaguna Please let me know if this works for you. Sorry for the amount of time it took to fix it.

![image](https://user-images.githubusercontent.com/85355/72346482-a8d4b600-3708-11ea-8cc3-296e8ab4363c.png)
