### ISSUE TITLE
Playground site is Down.

### ISSUE THREAD

**Issue by ITESaurabh** [lookfirst/mui-rff#707]
PLEASE NOTE, we currently only support MUI 4.x! Be sure that any issues you open are not related to 5.x!

**Describe the bug**
https://lookfirst.github.io/mui-rff/ is Not working

**To Reproduce**
1. Go to 'https://lookfirst.github.io/mui-rff/'
2. See error

**Expected behavior**
Website shoud be working 

**Screenshots**
![image](https://user-images.githubusercontent.com/50075159/162393672-fc67bfc5-dc6f-4c56-a142-96358924c04e.png)

**Desktop (please complete the following information):**
 - OS: Fedora 35
 - Browser Firefox, Chrome
 - Version 99, 100

**Additional context**
There is some Production level bug.

**Comment by lookfirst** [comment]
Ah yes, thank you!

```
The original text of the error you encountered:
Can not find utils in context. It looks like you forgot to wrap your component in LocalizationProvider, or pass dateAdapter prop directly.
```

I got caught by my own upgrade bug. =)

**Comment by ITESaurabh** [comment]
Site is still down though. maybe you forgot to deploy changes XD.

**Comment by lookfirst** [comment]
Yea, sorry, just haven't had time... you can see in my profile I commit a lot of code (but on other projects)... =) I made the change locally, just haven't had time to test it.

**Comment by yann-combarnous** [comment]
@lookfirst, I had implemented your recommendation for wrapping LocalizationProvider, but is seems that upgrading to     
* "@mui/lab": "5.0.0-alpha.77",
* "@mui/material": "5.6.1",
from
 * "@mui/lab": "5.0.0-alpha.75",
 * "@mui/material": "5.5.3",

Does prompt for the error again:
```
The original text of the error you encountered:
Can not find utils in context. It looks like you forgot to wrap your component in LocalizationProvider, or pass dateAdapter prop directly.
```

**Comment by lookfirst** [comment]
@yann-combarnous Thanks for the update. I'll take a look soon.

**Comment by lookfirst** [comment]
5.3.0 fixes this and also does the upgrade @yann-combarnous suggested.
