### ISSUE TITLE
React 18

### ISSUE THREAD

**Issue by lookfirst** [lookfirst/mui-rff#714]
I tried to set React 18 in the package.json dependencies and it broke all the tests with strange errors. Would love some community help with fixing that.

**Comment by yann-combarnous** [comment]
@lookfirst , in your dependencies, you depend on "@mui/styles", but based on the documentation page for this package it is not compatible with React 18 https://mui.com/system/styles/basics/. 

It seems that you should be using '@mui/material/styles'.

**Comment by stefanpl** [comment]
> Seems, as always, there is like 50 ways to do something and they are all confusing.

Pretty spot on :D 

Setting up a new project right now, really sad to see this is not working. But honestly no time whatsoever to provide a fix, so I'll wait patiently and hope 🙏

**Comment by CyanoFresh** [comment]
same, cannot use this library because of this issue

**Comment by wadsworj** [comment]
I have all the unit tests passing in pull request #842
just need to remove all the act() wrappers which I don't think are needed and everything seems to be passing.
However some of the snapshots.... not sure exactly if most of them are still passing or if all of them are broken.
For sure it looks like the DateTimePicker snapshots are missing the warning label.
Not sure if anyone is able to help with that or not...

**Comment by lookfirst** [comment]
v6.1.0 is released. It should have been 6.0.0, but the example app parcel build was failing. Then I did yarn publish --minor instead of --patch and got 6.1.0. whoops.

**Comment by primal100** [comment]
This is still not working because of the dependancy on  "@mui/styles"

https://mui.com/system/styles/basics/

"@mui/styles is not compatible with React.StrictMode or React 18".

The only use of mui/styles is in TestUtils.txt so I suppose it should be an easy fix.

**Comment by wadsworj** [comment]
@primal100 good catch - did you want to take a crack at removing that dependency or should I look into it?

**Comment by lookfirst** [comment]
I just prepped the fix, but late now where I'm at. I'll get this released tomorrow.

**Comment by lookfirst** [comment]
Released!

I also looked into upgrading to yarn v2... that's a mess because of the example app and dependencies around that... it seems this model of having a src directory and then an example app, isn't very well supported. Sigh.

**Comment by primal100** [comment]
Thanks for new release, @lookfirst however @mui/styles is listed as a dependency in package.json so it blocks upgrades to React 18. I'll try to remove it now and make a PR.

**Comment by lookfirst** [comment]
Sorry about that @primal100 ... just did another release. It is so amazing how software rots over time... especially web software...

**Comment by primal100** [comment]
Thanks its working now. Yes I am currently in the process of upgrading React 16, Material 4 and React-Router 5 to 18, 5 and 6 respectively and it's almost a total rewrite, especially Mui. And then working with dependencies to help them get to the same versions. It's a big change from working with Python and traditional programming languages.

**Comment by lookfirst** [comment]
I feel your pain.

One nice thing about typescript is the compiler.

Python... you have to have a lot of unit tests just to ensure that the code 'compiles' or doesn't have run time errors in production... I don't know how people deal with that with Python... I am a huge fan of compilers.
