### ISSUE TITLE
TextField label should be shrinked on focus

### ISSUE THREAD

**Issue by jgoux** [lookfirst/mui-rff#82]
Hello,

the TextField's label isn't shrinked on focus.

I think it should be as per material-ui documentation.

It seems that you control the shrinking [manually](https://github.com/lookfirst/mui-rff/blob/master/src/TextField.tsx#L48), I'm curious why?

**Comment by lookfirst** [comment]
hi @jgoux thanks for the issue.

yea, you're totally right, i goofed that up pretty badly and i'm not even sure why.

i'll work on making it match their site.

**Comment by lookfirst** [comment]
@jgoux This should be fixed now. Thanks for the report.
