### ISSUE TITLE
[feature] Toggle (Switch?) Button wrapper 

### ISSUE THREAD

**Issue by Lekha30** [lookfirst/mui-rff#83]
Hi there,
Is there a wrapper for Toggle button?

**Comment by lookfirst** [comment]
You mean a [Switch](https://material-ui.com/components/switches/)? Not yet, but happy to accept a contribution or I can add it when I have some time.

**Comment by lookfirst** [comment]
@Lekha30 Ping!

**Comment by popuguytheparrot** [comment]
Hi. I need Switch adapter too.

**Comment by lookfirst** [comment]
@popuguytheparrot Great thanks for the feedback. Since it scratches your itch today, do you want to take a stab at it and I can help?

**Comment by lookfirst** [comment]
Fixed with #121
