### ISSUE TITLE
[feature] Enable overriding of helperText (was: Make helperText default to " ")

### ISSUE THREAD

**Issue by jgoux** [lookfirst/mui-rff#84]
Hello,

I'm always bothered by the fields moving up/down when the error message appears. To prevent that, I usually define `helperText=" "` so the space is already defined and the fields stay at the same position when the error messages appear.

Do you think it's a good idea to initialize helperText like that by default? With the extra space it adds, I don't think we need `margin="normal"` anymore.

**Comment by lookfirst** [comment]
Hi @jgoux ... i pretty much agree with you. part of my motivation for defaulting `margin="normal"` was that it looks better by default. i feel like the spacing in the demo is quite nice. 

i also wanted the [codesandbox](https://codesandbox.io/s/react-final-form-material-ui-example-tqv09) to be pixel accurate [with the other project](https://codesandbox.io/s/react-final-form-material-ui-example-3u2jj). if you open both as tabs in one window and then switch back and forth, you can see they are the same.

i will play with helperText=" " and see what happens.

**Comment by lookfirst** [comment]
In my example app, I removed the `margin="normal"` from both checkboxes and radios. Then I defaulted to `helperText=" "`. As you can see the radio is too close to the error message.

![image](https://user-images.githubusercontent.com/85355/72659196-97ccc300-39ee-11ea-8afd-ec7db2140298.png)

I don't think MUI has an example form with everything in it with defaults. If they did, they might see these sorts of issues more clearly.

I'm not sure how to resolve it. I want things to just work without having to do a lot of styling work.

Thoughts?

**Comment by lookfirst** [comment]
`margin="normal"` for both:

![image](https://user-images.githubusercontent.com/85355/72659836-504b3480-39f8-11ea-96d8-c8891a077e4b.png)

**Comment by jgoux** [comment]
And what's happening with `margin="normal"` + the `helperText=" "` ?
Even if we don't go with the `helperText=" "` as default, it would be great to be able to set it in userland, either with a custom prop or by passing it a callback like `helperText={(meta) => /* compute helperText*/}`

**Comment by lookfirst** [comment]
> And what's happening with `margin="normal"` + the `helperText=" "` ?

That is the [second image above](https://github.com/lookfirst/mui-rff/issues/84#issuecomment-576720443).

**Comment by lookfirst** [comment]
> Even if we don't go with the `helperText=" "` as default, it would be great to be able to set it in userland, either with a custom prop or by passing it a callback like `helperText={(meta) => /* compute helperText*/}`

I can totally agree to that!

**Comment by jgoux** [comment]
Oops sorry I didn't understand it that way. 😄 
Personally I'd go with `helperText=" "` and no margin, or a custom one to fit my design system.
So in the end I think we should just let the current helperText default (this is the most expected default) but allow the callback approach to handle more exotic cases like mine. 👍

**Comment by lookfirst** [comment]
No problem! Just to explain to make sure we are on the same page... =)

For me, I want to use the default MUI settings as much as possible such that it looks good with minimal configuration and doesn't require custom margin setting because everyone does it differently. This desire unfortunately seems to be contrasting with what the defaults are for MUI (`margin="none"`), so I use `margin="normal"` as a MUI-RFF default and allow it to be overridden easily. You can see in the example that I don't have to do much overriding of the margins at all which I really like.

I also agree totally with anything that adds the ability to override and set whatever users want easily. I made a few hard coded things as a first pass and expect the community to tell me what they need (like you are doing). This is great feedback.

So... do you want to submit a PR or I can do it when I get some time...

**Comment by jgoux** [comment]
Sorry for the late answer @lookfirst !
I don't have much time right now but I'll try to submit something in the next couple of weeks.

**Comment by lookfirst** [comment]
@jgoux I just added the code from #115 which allows you to set the helperText. This probably fixes this issue, can you please confirm?

**Comment by lookfirst** [comment]
I'm going to close this one. I'm pretty happy with the way things are working at this point. Feel free to open another issue if there is something else that should be done.
