### ISSUE TITLE
Radios does not support styled-components

### ISSUE THREAD

**Issue by wojciech-skowronek** [lookfirst/mui-rff#92]
**Is your feature request related to a problem? Please describe.**
I cannot style the Radios component though styled-components library.

**Describe the solution you'd like**

Pass className prop to the root element of Radios component

**Comment by lookfirst** [comment]
@wojciech-skowronek Thanks for the report! Can you be a bit more specific though? 

You can pass in properties to all of the internal components...

```
<Radios label="Pick a gender" name="gender" required={required.gender} data={radioData} formControlProps={{className: 'foo'}} />,
```

**Comment by wojciech-skowronek** [comment]
You are right, but styled-components automatically adds the `className` prop to the component, so it would be very convenient if `RadiosProps` would contain `className` directly and pass it to the <FormControl />.

**Comment by lookfirst** [comment]
I agree about it being convenient, but I'd rather not add that to every single interface... especially in the case like radio where it is a number of components tied together... it would be hard to say which one to pass it into... did you want it on the `<FormControl>`, `<RadioGroup>`, `<FormControlLabel>`... etc ... I personally think it is much better to be explicit about it so I allow it to be overridden in those specific property objects.

If you'd like it to be more convenient for your development, it is easy to write your own thin wrapper around MUI-RFF too.

```tsx
function MyRadios(props) {
   return <Radios formControlProps={{className: 'foo'}} {...props} />;
}
```

I'm going to close this as not an issue just to keep my issue tracker clean, but that does not mean the discussion is being ended! Totally happy to keep on discussing things here. =)

**Comment by wojciech-skowronek** [comment]
I understand your point of view, but from the other hand it would be
consistent with MUI. Every single component of MUI supports that, providing
the possibility to work with styled-components.

It would be great if mui-rff could have similar API to MUI.

**Comment by lookfirst** [comment]
There is no single wrapper element in MUI for Radios. In MUI, you would set the `className` on the specific elements, which is exactly what MUI-RFF allows for. I wouldn't even know which element you'd want to pass the `className` onto as it could be 3 different elements (at a minimum). This same issue is reflected with many of the other elements as well (Checkboxes, and Select are prime examples).

**Comment by wojciech-skowronek** [comment]
You would need to pass it to the root element. This will allow a developer
to attach styles to any element inside. Exactly same way this works for
MUI.

**Comment by lookfirst** [comment]
Sorry, but it isn't the same because you're adding the `className` to the `<FormControl>` element. 

For this discussion, we are boiling the difference down to:

```tsx
<Radios formControlProps={{className: 'foo'}}>
```

and

```tsx
<Radios className='foo'>
```

Personally, I prefer to be explicit about what elements I'm putting `className` on (the first example).

[As I mentioned before](https://github.com/lookfirst/mui-rff/issues/92#issuecomment-578908014), if you'd like a different interface, it is easy enough to provide a one line wrapper that you can use. In fact, I would suggest it anyway because then you can make design changes more globally with a single change instead of having to define the `className` each time you use the component.
