### ISSUE TITLE
Set variant='standard' on DatePicker 

### ISSUE THREAD

**Issue by stefc** [lookfirst/mui-rff#920]
I want to set the variant of the TextField of a DatePicker to the value='standard' for archive the same look for all of my input elements on a form. Right now the only solution for this is to use the 'renderInput' property of ```DatePicker```

```
<DateTimePicker
          label="Date&Time picker"
          value={value}
          onChange={handleChange}
          renderInput={(params) => <TextField {...params} variant='standard'/>}
       />
``` 

in ```mui-rff``` this isn't possible because they use the renderInput property by their own and so I don't have any chance to archive this. 

I'll suggest to add the 'variant' property to your DatePickerProps and then assign it to the TextField inside your own renderInput. 

https://codesandbox.io/s/q3lz2r?file=/demo.tsx:1550-1749

![image](https://user-images.githubusercontent.com/464696/203813438-c332167e-3318-4a30-ad33-9509a9960478.png)

**Comment by lookfirst** [comment]
@stefc Thanks for the new issue. I wonder if there is some way to get the `params` field to pass that in?

**Comment by stefc** [comment]
I currently solve the problem with made a copy of DatePicker.tsx and add one simple line into the source code

```ts
renderInput={(inputProps) => (
	<TextField
		{...inputProps}
		fullWidth={true}
                variant="standard" // fix the above problem until 'mui-rff' have a solution for it or waiting for MUI v6
		helperText={isError ? error || submitError : helperText}
 	        error={inputProps.error || isError}
		name={name}
                .....
```

![image](https://user-images.githubusercontent.com/464696/203905844-37b9612e-e608-42f2-800e-8e149bb2b26c.png)

**Comment by kjellski** [comment]
I've put in a PR that enables us to just pass the `TextFieldProps` along... 😃
