### ISSUE TITLE
Loosen helperText type

### ISSUE THREAD

**Issue by namoscato** [lookfirst/mui-rff#956]
**Is your feature request related to a problem? Please describe.**

Arguably a bug, but the `helperText` prop type is currently a `string`.

**Describe the solution you'd like**

Loosen `helperText` prop type to `React.ReactNode` given it's seemingly passed as [`FormHelperText`](https://mui.com/material-ui/api/form-helper-text/) `children`

**Describe alternatives you've considered**

N/A

**Additional context**

On glance, `helperText` is just passed in as a `children` prop, so the the proposed change should be fine:

https://github.com/lookfirst/mui-rff/blob/87a742246fc0cbdc1fa33530abc30886b7f9761f/src/Util.tsx#L16-L17

**Comment by lookfirst** [comment]
Hey! Happy new year. Thanks for the comment.

Yea, that looks like a valid change. Want to submit a PR for it?

**Comment by namoscato** [comment]
Happy New Year to you too!

> Want to submit a PR for it?

Yeah, I can probably grab it within the next ~week.
