### ISSUE TITLE
Autocomplete regression in 6.1.3

### ISSUE THREAD

**Issue by yann-combarnous** [lookfirst/mui-rff#974]
**Describe the bug**

This change breaks MUI-RFF for AutoComplete with the "multiple" property:
https://github.com/lookfirst/mui-rff/commit/b2c25438486afad688560d813ce687cc6d782c6d

See https://github.com/mui/material-ui/blame/master/packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.js#L992

**To Reproduce**
- Add an Autocomplete with "multiple" property
- run the code
- it complains that value.length does not exist on null value (which was introduced above)

**Expected behavior**
No error

**Comment by yann-combarnous** [comment]
Confirmed here: https://mui.com/material-ui/api/autocomplete/, quote for « multiple » property: « If true, value must be an array and the menu will support multiple selections. »

But the mui-rff change above sometimes set ms value to null, which is not supported.

**Comment by lookfirst** [comment]
Ah crap, sorry about that. I should have done a deeper dive on things.

I'll revert asap (with a new release) and we can re-evaluate with another PR.

**Comment by lookfirst** [comment]
For now, just pin to the previous version in your package.json.

**Comment by kjellski** [comment]
Got it, sorry guys - my fault. We missed a test covering this, I'm working on it right away...

**Comment by lookfirst** [comment]
@kjellski Ok, looks like you're going to get to this before I can get time to release... so rolling forward would be best probably... thanks!

**Comment by kjellski** [comment]
#979 - once again, sorry for the regression, I hope this provides a proper fix - have a look yourself please and @yann-combarnous if you have time, check it as well 👍

**Comment by lookfirst** [comment]
6.1.4 has been released. Sorry about that @yann-combarnous and thanks so much for the fast response @kjellski. Excellent work all.

**Comment by yann-combarnous** [comment]
> 6.1.4 has been released. Sorry about that @yann-combarnous and thanks so much for the fast response @kjellski. Excellent work all.

Thx guys for the quick turnaround ! Works for me now. No worry, Autocomplete is a pretty complex component.
